/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ;
typedef struct tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA;
typedef struct tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw;
typedef struct tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg;
typedef struct tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw;
typedef struct tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw;
typedef struct tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ;
typedef struct tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA;
typedef struct Exception Exception;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ;
typedef struct tySequence__FkvojUQdPjfk5uWBVYh8ng tySequence__FkvojUQdPjfk5uWBVYh8ng;
typedef struct tySequence__FkvojUQdPjfk5uWBVYh8ng_Content tySequence__FkvojUQdPjfk5uWBVYh8ng_Content;
typedef struct tySequence__mGPxctZWGqgqUCCIeok9ccg tySequence__mGPxctZWGqgqUCCIeok9ccg;
typedef struct tySequence__mGPxctZWGqgqUCCIeok9ccg_Content tySequence__mGPxctZWGqgqUCCIeok9ccg_Content;
typedef struct tyObject_Option__PIf21JqAO9ck9bbGJvgpfL0Q tyObject_Option__PIf21JqAO9ck9bbGJvgpfL0Q;
typedef struct tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg;
typedef struct tyObject_FuturecolonObjectType___fBy0voJzGMAH1iG9cYhPxLw tyObject_FuturecolonObjectType___fBy0voJzGMAH1iG9cYhPxLw;
typedef struct tySequence__m8dDOEi8dz59aSYynu9cxGsQ tySequence__m8dDOEi8dz59aSYynu9cxGsQ;
typedef struct tySequence__m8dDOEi8dz59aSYynu9cxGsQ_Content tySequence__m8dDOEi8dz59aSYynu9cxGsQ_Content;
typedef struct tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA;
typedef struct tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw;
typedef struct tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw;
typedef struct tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw;
typedef struct tyObject_TableSnapshot__baF3vyipl6sHCBe0ssDF4w tyObject_TableSnapshot__baF3vyipl6sHCBe0ssDF4w;
typedef struct tySequence__ldrtOldcIK4ucnaUwHkEDw tySequence__ldrtOldcIK4ucnaUwHkEDw;
typedef struct tySequence__ldrtOldcIK4ucnaUwHkEDw_Content tySequence__ldrtOldcIK4ucnaUwHkEDw_Content;
typedef struct tySequence__EcJqHR4nqQX9cAU1lo2nygg tySequence__EcJqHR4nqQX9cAU1lo2nygg;
typedef struct tySequence__EcJqHR4nqQX9cAU1lo2nygg_Content tySequence__EcJqHR4nqQX9cAU1lo2nygg_Content;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
typedef struct tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ;
typedef struct tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q;
typedef struct tySequence__OaHwijEm2KHEod7LMrnNzA tySequence__OaHwijEm2KHEod7LMrnNzA;
typedef struct tySequence__OaHwijEm2KHEod7LMrnNzA_Content tySequence__OaHwijEm2KHEod7LMrnNzA_Content;
typedef struct tySequence__hQIfAYFnNr44cTZfDXJxLQ tySequence__hQIfAYFnNr44cTZfDXJxLQ;
typedef struct tySequence__hQIfAYFnNr44cTZfDXJxLQ_Content tySequence__hQIfAYFnNr44cTZfDXJxLQ_Content;
typedef struct tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ;
typedef struct tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw;
typedef struct tyObject_ExistingColumn__9cXXLEYHRHskEuaM5izPvdA tyObject_ExistingColumn__9cXXLEYHRHskEuaM5izPvdA;
typedef struct tyObject_ExistingIndex__MvBnA2LALnDrcieE9bt5uLQ tyObject_ExistingIndex__MvBnA2LALnDrcieE9bt5uLQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__732F4NLvyCWp6BvEC0QQAg tyTuple__732F4NLvyCWp6BvEC0QQAg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA {
	RootObj Sup;
};
typedef NU8 tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA {
	tyProc__HzVCwACFYM9cx9aV62PdjtuA function;
	tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA* next;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ {
	RootObj Sup;
	tyObject_CallbackList__Wead9aHTeBQoJLLtbe5MgfA callbacks;
	NIM_BOOL finished;
	Exception* error;
	NimStringV2 errorStackTrace;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ stackTrace;
	NI id;
	NimStringV2 fromProc;
};
struct tySequence__FkvojUQdPjfk5uWBVYh8ng {
  NI len; tySequence__FkvojUQdPjfk5uWBVYh8ng_Content* p;
};
struct tySequence__mGPxctZWGqgqUCCIeok9ccg {
  NI len; tySequence__mGPxctZWGqgqUCCIeok9ccg_Content* p;
};
struct tyObject_Option__PIf21JqAO9ck9bbGJvgpfL0Q {
	NI64 val;
	NIM_BOOL has;
};
struct tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ {
	tySequence__FkvojUQdPjfk5uWBVYh8ng columns;
	tySequence__mGPxctZWGqgqUCCIeok9ccg rows;
	NI affectedRowCount;
	tyObject_Option__PIf21JqAO9ck9bbGJvgpfL0Q lastInsertRowId;
};
struct tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg {
	tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ Sup;
	tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ value;
};
struct tySequence__m8dDOEi8dz59aSYynu9cxGsQ {
  NI len; tySequence__m8dDOEi8dz59aSYynu9cxGsQ_Content* p;
};
struct tyObject_FuturecolonObjectType___fBy0voJzGMAH1iG9cYhPxLw {
	tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ Sup;
	tySequence__m8dDOEi8dz59aSYynu9cxGsQ value;
};
struct tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA {
	tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ Sup;
};
struct tySequence__ldrtOldcIK4ucnaUwHkEDw {
  NI len; tySequence__ldrtOldcIK4ucnaUwHkEDw_Content* p;
};
struct tySequence__EcJqHR4nqQX9cAU1lo2nygg {
  NI len; tySequence__EcJqHR4nqQX9cAU1lo2nygg_Content* p;
};
struct tyObject_TableSnapshot__baF3vyipl6sHCBe0ssDF4w {
	NimStringV2 table;
	tySequence__ldrtOldcIK4ucnaUwHkEDw columns;
	tySequence__EcJqHR4nqQX9cAU1lo2nygg indexes;
};
struct tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw {
	tyObject_TableSnapshot__baF3vyipl6sHCBe0ssDF4w val;
	NIM_BOOL has;
};
struct tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw {
	tyObject_FutureBasecolonObjectType___dJIliYKephQFYVl6LzDYBQ Sup;
	tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw value;
};
typedef NU8 tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw {
	tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw kind;
union{
	struct {
	NI64 intValue;
} _kind_2;
	struct {
	NF floatValue;
} _kind_3;
	struct {
	NimStringV2 textValue;
} _kind_4;
	struct {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blobValue;
} _kind_5;
};
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
struct tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ {
	NimStringV2 name;
	NimStringV2 decltype_0;
};
struct tySequence__FkvojUQdPjfk5uWBVYh8ng_Content { NI cap; tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ data[SEQ_DECL_SIZE]; };
struct tySequence__OaHwijEm2KHEod7LMrnNzA {
  NI len; tySequence__OaHwijEm2KHEod7LMrnNzA_Content* p;
};
struct tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q {
	tySequence__OaHwijEm2KHEod7LMrnNzA data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__mGPxctZWGqgqUCCIeok9ccg_Content { NI cap; tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q data[SEQ_DECL_SIZE]; };
struct tySequence__hQIfAYFnNr44cTZfDXJxLQ {
  NI len; tySequence__hQIfAYFnNr44cTZfDXJxLQ_Content* p;
};
struct tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg {
	NimStringV2 sql;
	tySequence__hQIfAYFnNr44cTZfDXJxLQ params;
};
struct tySequence__m8dDOEi8dz59aSYynu9cxGsQ_Content { NI cap; tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ data[SEQ_DECL_SIZE]; };
struct tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ {
	NI val;
	NIM_BOOL has;
};
struct tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw {
	NimStringV2 val;
	NIM_BOOL has;
};
struct tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw {
	NimStringV2 name;
	NimStringV2 nimType;
	NimStringV2 dbType;
	NIM_BOOL primary;
	NIM_BOOL autoincrement;
	NIM_BOOL unique;
	NIM_BOOL indexed;
	tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ maxLength;
	tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw defaultValue;
};
struct tyObject_ExistingColumn__9cXXLEYHRHskEuaM5izPvdA {
	NimStringV2 name;
	NimStringV2 dbType;
	NIM_BOOL notNull;
	tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw defaultValue;
	NIM_BOOL primaryKey;
};
struct tySequence__ldrtOldcIK4ucnaUwHkEDw_Content { NI cap; tyObject_ExistingColumn__9cXXLEYHRHskEuaM5izPvdA data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_ExistingIndex__MvBnA2LALnDrcieE9bt5uLQ {
	NimStringV2 name;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ columns;
	NIM_BOOL unique;
};
struct tySequence__EcJqHR4nqQX9cAU1lo2nygg_Content { NI cap; tyObject_ExistingIndex__MvBnA2LALnDrcieE9bt5uLQ data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tyTuple__732F4NLvyCWp6BvEC0QQAg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw Field3;
};
struct tySequence__OaHwijEm2KHEod7LMrnNzA_Content { NI cap; tyTuple__732F4NLvyCWp6BvEC0QQAg data[SEQ_DECL_SIZE]; };
struct tySequence__hQIfAYFnNr44cTZfDXJxLQ_Content { NI cap; tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, chckNilDisp)(void* p_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u332)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u322)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u312)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u16)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u335)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0, NimStringV2 ident_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u325)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0, NimStringV2 ident_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u315)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0, NimStringV2 ident_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u83)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, NimStringV2 ident_p1);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u339)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u329)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u319)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u90)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg*, execute__OOZsrcZnimtraZdriverZbase_u8)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, NimStringV2 sql_p1, tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw* args_p2, NI args_p2Len_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg*, execute__OOZsrcZnimtraZdriverZbase_u31)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg* statement_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___fBy0voJzGMAH1iG9cYhPxLw*, executeBatch__OOZsrcZnimtraZdriverZbase_u815)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg* statements_p1, NI statements_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg*, query__OOZsrcZnimtraZdriverZbase_u824)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, NimStringV2 sql_p1, tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw* args_p2, NI args_p2Len_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg*, query__OOZsrcZnimtraZdriverZbase_u842)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg* statement_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, sync__OOZsrcZnimtraZdriverZbase_u933)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, close__OOZsrcZnimtraZdriverZbase_u1058)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u131)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u106)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u81)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u55)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u4013)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u3706)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u3231)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u3081)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw*, getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u10400)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw*, getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u6907)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw*, getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u5996)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw*, getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u5392)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpnativesocketsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__lA3r615eP744ZZpN6IBo2g_3 = { 2 | NIM_STRLIT_FLAG, "ok" };
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__lA3r615eP744ZZpN6IBo2g_2 = {{2, (NimStrPayload*)&TM__lA3r615eP744ZZpN6IBo2g_3}}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");
	nimlf_(268, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u81)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("name", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(114, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/chcks.nim");	chckNilDisp(dialect_p0);
	nimlf_(14, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)))) goto LA3_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = name__OOZsrcZnimtraZdialects_u332(((tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ*) (dialect_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)))) goto LA6_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = name__OOZsrcZnimtraZdialects_u322(((tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA*) (dialect_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)))) goto LA9_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = name__OOZsrcZnimtraZdialects_u312(((tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw*) (dialect_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 1, 2846643200)))) goto LA12_;
		result = name__OOZsrcZnimtraZdialects_u16(dialect_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA12_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u88)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, NimStringV2 ident_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("quoteIdent", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(114, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/chcks.nim");	chckNilDisp(dialect_p0);
	nimlf_(17, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)))) goto LA3_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = quoteIdent__OOZsrcZnimtraZdialects_u335(((tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ*) (dialect_p0)), ident_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)))) goto LA6_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = quoteIdent__OOZsrcZnimtraZdialects_u325(((tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA*) (dialect_p0)), ident_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)))) goto LA9_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = quoteIdent__OOZsrcZnimtraZdialects_u315(((tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw*) (dialect_p0)), ident_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 1, 2846643200)))) goto LA12_;
		result = quoteIdent__OOZsrcZnimtraZdialects_u83(dialect_p0, ident_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA12_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u112)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0) {
	tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w result;
NIM_BOOL* nimErr_;
	nimfr_("placeholderStyle", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
{nimErr_ = nimErrorFlag();
	result = (tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w)0;
	nimlf_(114, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/chcks.nim");	chckNilDisp(dialect_p0);
	nimlf_(20, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)))) goto LA3_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = placeholderStyle__OOZsrcZnimtraZdialects_u339(((tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ*) (dialect_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)))) goto LA6_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = placeholderStyle__OOZsrcZnimtraZdialects_u329(((tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA*) (dialect_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)))) goto LA9_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = placeholderStyle__OOZsrcZnimtraZdialects_u319(((tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw*) (dialect_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 1, 2846643200)))) goto LA12_;
		result = placeholderStyle__OOZsrcZnimtraZdialects_u90(dialect_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA12_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg*, execute__OOZsrcZnimtraZdriverZbase_u16)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, NimStringV2 sql_p1, tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw* args_p2, NI args_p2Len_0) {
	tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg* result;
NIM_BOOL* nimErr_;
	nimfr_("execute", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/driver/base.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = execute__OOZsrcZnimtraZdriverZbase_u8(db_p0, sql_p1, args_p2, args_p2Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg*, execute__OOZsrcZnimtraZdriverZbase_u813)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg* statement_p1) {
	tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = execute__OOZsrcZnimtraZdriverZbase_u31(db_p0, statement_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___fBy0voJzGMAH1iG9cYhPxLw*, executeBatch__OOZsrcZnimtraZdriverZbase_u822)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg* statements_p1, NI statements_p1Len_0) {
	tyObject_FuturecolonObjectType___fBy0voJzGMAH1iG9cYhPxLw* result;
NIM_BOOL* nimErr_;
	nimfr_("executeBatch", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/driver/base.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = executeBatch__OOZsrcZnimtraZdriverZbase_u815(db_p0, statements_p1, statements_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg*, query__OOZsrcZnimtraZdriverZbase_u831)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, NimStringV2 sql_p1, tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw* args_p2, NI args_p2Len_0) {
	tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg* result;
NIM_BOOL* nimErr_;
	nimfr_("query", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/driver/base.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = query__OOZsrcZnimtraZdriverZbase_u824(db_p0, sql_p1, args_p2, args_p2Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg*, query__OOZsrcZnimtraZdriverZbase_u922)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0, tyObject_SqlStatement__BL3mO15epKvzhe69cjAs8Vg* statement_p1) {
	tyObject_FuturecolonObjectType___PfQbshJIMUVcI9bNr0Vpmyg* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = query__OOZsrcZnimtraZdriverZbase_u842(db_p0, statement_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, sync__OOZsrcZnimtraZdriverZbase_u1047)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0) {
	tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = sync__OOZsrcZnimtraZdriverZbase_u933(db_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, close__OOZsrcZnimtraZdriverZbase_u1134)(tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p0) {
	tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = close__OOZsrcZnimtraZdriverZbase_u1058(db_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u79)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("columnDefinitionSqlImpl", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(114, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/chcks.nim");	chckNilDisp(dialect_p0);
	nimlf_(45, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)))) goto LA3_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u131(((tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ*) (dialect_p0)), field_p1, includePrimaryAndUnique_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)))) goto LA6_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u106(((tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA*) (dialect_p0)), field_p1, includePrimaryAndUnique_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)))) goto LA9_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u81(((tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw*) (dialect_p0)), field_p1, includePrimaryAndUnique_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 1, 2846643200)))) goto LA12_;
		result = columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u55(dialect_p0, field_p1, includePrimaryAndUnique_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA12_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA*, ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u3220)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2) {
	tyObject_FuturecolonObjectType___2Nuq2jQawGsi4IjCrz13kA* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	chckNilDisp(dialect_p0);
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)))) goto LA3_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u4013(((tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ*) (dialect_p0)), db_p1, tableName_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)))) goto LA6_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u3706(((tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA*) (dialect_p0)), db_p1, tableName_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)))) goto LA9_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u3231(((tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw*) (dialect_p0)), db_p1, tableName_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 1, 2846643200)))) goto LA12_;
		result = ensureMigrationsTableImpl__OOZsrcZnimtraZmigrations_u3081(dialect_p0, db_p1, tableName_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA12_: ;
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw*, getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u5985)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, tyObject_DbConnectioncolonObjectType___jRTv0PncfjvGwiw5Eybnbw* db_p1, NimStringV2 tableName_p2) {
	tyObject_FuturecolonObjectType___MLOMWxZzskoeZyj9cQrv7Cw* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	chckNilDisp(dialect_p0);
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)))) goto LA3_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 4135674112)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u10400(((tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ*) (dialect_p0)), db_p1, tableName_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)))) goto LA6_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 3903579392)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u6907(((tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA*) (dialect_p0)), db_p1, tableName_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)))) goto LA9_;
		if (dialect_p0 && !isObjDisplayCheck((*dialect_p0).Sup.m_type, 2, 1742608384)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		result = getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u5996(((tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw*) (dialect_p0)), db_p1, tableName_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
	{
		if (!((dialect_p0) && (isObjDisplayCheck((*dialect_p0).Sup.m_type, 1, 2846643200)))) goto LA12_;
		result = getTableSnapshotImpl__OOZsrcZnimtraZmigrations_u5392(dialect_p0, db_p1, tableName_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA12_: ;
LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpnativesocketsdotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	nimfr_("import_core_only", "/Users/nakagawa_shota/repo/valit/nimtra/tests/import_core_only.nim");
	nimlf_(3, "/Users/nakagawa_shota/repo/valit/nimtra/tests/import_core_only.nim");	echoBinSafe(TM__lA3r615eP744ZZpN6IBo2g_2, 1);
	nimTestErrorFlag();
	popFrame();
}
}

