/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyTuple__KgCfVHUs0cYxgmkyevnAYA tyTuple__KgCfVHUs0cYxgmkyevnAYA;
typedef struct tySequence__MrZxSiufAn89cqCs8IPtPpg tySequence__MrZxSiufAn89cqCs8IPtPpg;
typedef struct tySequence__MrZxSiufAn89cqCs8IPtPpg_Content tySequence__MrZxSiufAn89cqCs8IPtPpg_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (tyTuple__KgCfVHUs0cYxgmkyevnAYA x_p0, tyTuple__KgCfVHUs0cYxgmkyevnAYA y_p1, void* ClE_0);
void* ClE_0;
} tyProc__ukhiUvx6x4GoTv7p2W8XvQ;
typedef NU8 tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg;
struct tySequence__MrZxSiufAn89cqCs8IPtPpg {
  NI len; tySequence__MrZxSiufAn89cqCs8IPtPpg_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__KgCfVHUs0cYxgmkyevnAYA {
	NI64 Field0;
	NimStringV2 Field1;
};
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_8) (tyTuple__KgCfVHUs0cYxgmkyevnAYA x_p0, tyTuple__KgCfVHUs0cYxgmkyevnAYA y_p1);
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_13) (tyTuple__KgCfVHUs0cYxgmkyevnAYA x_p0, tyTuple__KgCfVHUs0cYxgmkyevnAYA y_p1);
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (tyTuple__QeWl6B6ffS4pU6WWrtcrDw x_p0, tyTuple__QeWl6B6ffS4pU6WWrtcrDw y_p1, void* ClE_0);
void* ClE_0;
} tyProc__TNYmJG2tqVAKrEI5hlMXCg;
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_28) (tyTuple__QeWl6B6ffS4pU6WWrtcrDw x_p0, tyTuple__QeWl6B6ffS4pU6WWrtcrDw y_p1);
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_32) (tyTuple__QeWl6B6ffS4pU6WWrtcrDw x_p0, tyTuple__QeWl6B6ffS4pU6WWrtcrDw y_p1);
struct tySequence__MrZxSiufAn89cqCs8IPtPpg_Content { NI cap; tyTuple__KgCfVHUs0cYxgmkyevnAYA data[SEQ_DECL_SIZE]; };
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__MrZxSiufAn89cqCs8IPtPpg, newSeq__OOZsrcZnimtraZmigrations_u6223)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__OOZsrcZnimtraZmigrations_u6386)(tyTuple__KgCfVHUs0cYxgmkyevnAYA* a_p0, NI a_p0Len_0, tyTuple__KgCfVHUs0cYxgmkyevnAYA* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__ukhiUvx6x4GoTv7p2W8XvQ cmp_p5, tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg order_p6);
static N_INLINE(NI, star___pureZalgorithm_u8)(NI x_p0, tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg order_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZnimtraZmigrations_u6310)(tyTuple__KgCfVHUs0cYxgmkyevnAYA* dest_p0, tyTuple__KgCfVHUs0cYxgmkyevnAYA src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZmigrations_u6298)(tyTuple__KgCfVHUs0cYxgmkyevnAYA* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0);
static N_INLINE(NF, abs__system_u5241)(NF x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u6346)(tySequence__MrZxSiufAn89cqCs8IPtPpg dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__4eRCaZmrYLLw2k30GPTiMw, newSeq__OOZsrcZnimtraZmigrations_u7830)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__OOZsrcZnimtraZmigrations_u9565)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* a_p0, NI a_p0Len_0, tyTuple__QeWl6B6ffS4pU6WWrtcrDw* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__TNYmJG2tqVAKrEI5hlMXCg cmp_p5, tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg order_p6);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZnimtraZmigrations_u7251)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0, tyTuple__QeWl6B6ffS4pU6WWrtcrDw src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZmigrations_u7239)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u7176)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0);
static const struct {
  NI cap; NIM_CHAR data[94+1];
} TM__JdC9c6SaUkvO1XjYuWP1JWQ_9 = { 94 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim(338, 3) `j <= m` " };
static const NimStringV2 TM__JdC9c6SaUkvO1XjYuWP1JWQ_10 = {94, (NimStrPayload*)&TM__JdC9c6SaUkvO1XjYuWP1JWQ_9};
static const NimStringV2 TM__JdC9c6SaUkvO1XjYuWP1JWQ_29 = {94, (NimStrPayload*)&TM__JdC9c6SaUkvO1XjYuWP1JWQ_9};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1634)(NI* a_p0, NI a_p0Len_0, NI value_p1) {
	NI xX60gensym170__1;
	nimfr_("fill", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");
{	nimlf_(72, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");	xX60gensym170__1 = ((NI)0);
	{
		nimln_(98);		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_2;
			nimln_(73);			nimln_(98);			if (!(xX60gensym170__1 <= (a_p0Len_0-1))) goto LA2;
			nimln_(74);			if (xX60gensym170__1 < 0 || xX60gensym170__1 >= a_p0Len_0){ raiseIndexError2(xX60gensym170__1,a_p0Len_0-1); goto BeforeRet_;
			}
			nimln_(98);			a_p0[xX60gensym170__1] = value_p1;
			nimln_(75);			if (nimAddInt(xX60gensym170__1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_2)) { raiseOverflow(); goto BeforeRet_;
			};
			xX60gensym170__1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_2);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, star___pureZalgorithm_u8)(NI x_p0, tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg order_p1) {
	NI result;
	NI y_1;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_5;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_6;
	nimfr_("*", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");
{	result = (NI)0;
	nimln_(68);	if (nimSubInt(order_p1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_5)) { raiseOverflow(); goto BeforeRet_;
	};
	y_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_5);
	nimln_(69);	if (nimSubInt((NI)(x_p0 ^ y_1), y_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_6)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_6);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__OOZsrcZnimtraZmigrations_u6386)(tyTuple__KgCfVHUs0cYxgmkyevnAYA* a_p0, NI a_p0Len_0, tyTuple__KgCfVHUs0cYxgmkyevnAYA* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__ukhiUvx6x4GoTv7p2W8XvQ cmp_p5, tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg order_p6) {
	NI j_1;
	NI bb_1;
	NI i_1;
	NI k_1;
NIM_BOOL* nimErr_;
	nimfr_("mergeAlt", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");
{nimErr_ = nimErrorFlag();
	nimln_(335);	{
		NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_7;
		NI T3_;
		NI T4_;
		if (m_p3 < 0 || m_p3 >= a_p0Len_0){ raiseIndexError2(m_p3,a_p0Len_0-1); goto BeforeRet_;
		}
		if (nimAddInt(m_p3, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_7)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_7) < 0 || (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_7) >= a_p0Len_0){ raiseIndexError2((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_7),a_p0Len_0-1); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = cmp_p5.ClE_0? cmp_p5.ClP_0(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_7)], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_8)(cmp_p5.ClP_0))(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_7)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T4_ = (NI)0;
		T4_ = star___pureZalgorithm_u8(T3_, order_p6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T4_ <= ((NI)0))) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(336);	j_1 = lo_p2;
	nimln_(338);	{
		if (!!((j_1 <= m_p3))) goto LA9_;
		failedAssertImpl__stdZassertions_u95(TM__JdC9c6SaUkvO1XjYuWP1JWQ_10);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	nimln_(340);	bb_1 = ((NI)0);
	{
		nimln_(341);		while (1) {
			tyTuple__KgCfVHUs0cYxgmkyevnAYA T13_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_11;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_12;
			if (!(j_1 <= m_p3)) goto LA12;
			nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (bb_1 < 0 || bb_1 >= b_p1Len_0){ raiseIndexError2(bb_1,b_p1Len_0-1); goto BeforeRet_;
			}
			nimlf_(323, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");			if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
			}
			T13_ = a_p0[j_1];
			eqwasMoved___OOZsrcZnimtraZmigrations_u6298((&a_p0[j_1]));
			nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			eqsink___OOZsrcZnimtraZmigrations_u6310((&b_p1[bb_1]), T13_);
			nimlf_(343, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");			if (nimAddInt(bb_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_11)) { raiseOverflow(); goto BeforeRet_;
			};
			bb_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_11);
			nimln_(344);			if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_12)) { raiseOverflow(); goto BeforeRet_;
			};
			j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_12);
		} LA12: ;
	}
	nimln_(348);	i_1 = ((NI)0);
	nimln_(349);	k_1 = lo_p2;
	{
		nimln_(351);		while (1) {
			NIM_BOOL T16_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_16;
			T16_ = (NIM_BOOL)0;
			T16_ = (k_1 < j_1);
			if (!(T16_)) goto LA17_;
			T16_ = (j_1 <= hi_p4);
LA17_: ;
			if (!T16_) goto LA15;
			nimln_(352);			{
				NI T20_;
				NI T21_;
				tyTuple__KgCfVHUs0cYxgmkyevnAYA T24_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_14;
				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				T20_ = (NI)0;
				T20_ = cmp_p5.ClE_0? cmp_p5.ClP_0(b_p1[i_1], a_p0[j_1], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_13)(cmp_p5.ClP_0))(b_p1[i_1], a_p0[j_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T21_ = (NI)0;
				T21_ = star___pureZalgorithm_u8(T20_, order_p6);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T21_ <= ((NI)0))) goto LA22_;
				nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				nimlf_(323, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				T24_ = b_p1[i_1];
				eqwasMoved___OOZsrcZnimtraZmigrations_u6298((&b_p1[i_1]));
				nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqsink___OOZsrcZnimtraZmigrations_u6310((&a_p0[k_1]), T24_);
				nimlf_(354, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");				if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_14)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_14);
			}
			goto LA18_;
LA22_: ;
			{
				tyTuple__KgCfVHUs0cYxgmkyevnAYA T26_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_15;
				nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				nimlf_(323, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				T26_ = a_p0[j_1];
				eqwasMoved___OOZsrcZnimtraZmigrations_u6298((&a_p0[j_1]));
				nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqsink___OOZsrcZnimtraZmigrations_u6310((&a_p0[k_1]), T26_);
				nimlf_(357, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");				if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_15)) { raiseOverflow(); goto BeforeRet_;
				};
				j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_15);
			}
LA18_: ;
			nimln_(358);			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_16)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_16);
		} LA15: ;
	}
	{
		nimln_(361);		while (1) {
			tyTuple__KgCfVHUs0cYxgmkyevnAYA T29_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_17;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_18;
			if (!(k_1 < j_1)) goto LA28;
			nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
			}
			nimlf_(323, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");			if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
			}
			T29_ = b_p1[i_1];
			eqwasMoved___OOZsrcZnimtraZmigrations_u6298((&b_p1[i_1]));
			nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			eqsink___OOZsrcZnimtraZmigrations_u6310((&a_p0[k_1]), T29_);
			nimlf_(363, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_17)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_17);
			nimln_(364);			if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_18)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_18);
		} LA28: ;
	}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0) {
	NF result;
	nimfr_("toFloat", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	nimlf_(1302, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__system_u5241)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toFloat__system_u1705(a_p0);
	T2_ = (NF)0;
	T2_ = toFloat__system_u1705(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toFloat__system_u1705(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__system_u5241(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__system_u5241(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, sort__OOZsrcZnimtraZmigrations_u6194)(tyTuple__KgCfVHUs0cYxgmkyevnAYA* a_p0, NI a_p0Len_0, tyProc__ukhiUvx6x4GoTv7p2W8XvQ cmp_p1, tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg order_p2) {
	tySequence__MrZxSiufAn89cqCs8IPtPpg b_1;
	NI n_1;
	NI s_1;
NIM_BOOL* nimErr_;
	nimfr_("sort", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");
{nimErr_ = nimErrorFlag();
	b_1.len = 0; b_1.p = NIM_NIL;
	nimlf_(411, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");	n_1 = a_p0Len_0;
	nimln_(412);	if (((NI)((n_1) / (((NI)2)))) < ((NI)0) || ((NI)((n_1) / (((NI)2)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((n_1) / (((NI)2))), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	b_1 = newSeq__OOZsrcZnimtraZmigrations_u6223(((NI)((n_1) / (((NI)2)))));
	nimln_(413);	s_1 = ((NI)1);
	{
		nimln_(414);		while (1) {
			NI m_1;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_3;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_4;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_24;
			if (!(s_1 < n_1)) goto LA2;
			nimln_(415);			if (nimSubInt(n_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_3)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimSubInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_3), s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_4)) { raiseOverflow(); goto BeforeRet_;
			};
			m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_4);
			{
				nimln_(416);				while (1) {
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_19;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_20;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_21;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_22;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_23;
					if (!(((NI)0) <= m_1)) goto LA4;
					nimln_(417);					if (nimSubInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_19)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_19), ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_20)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_21)) { raiseOverflow(); goto BeforeRet_;
					};
					mergeAlt__OOZsrcZnimtraZmigrations_u6386(a_p0, a_p0Len_0, ((b_1).p) ? (b_1.p->data) : NIM_NIL, b_1.len, (((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_20) >= ((NI)0)) ? (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_20) : ((NI)0)), m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_21), cmp_p1, order_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(418);					if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_22)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt(m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_22), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_23)) { raiseOverflow(); goto BeforeRet_;
					};
					m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_23);
				} LA4: ;
			}
			nimln_(419);			if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_24)) { raiseOverflow(); goto BeforeRet_;
			};
			s_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_24);
		} LA2: ;
	}
	nimlf_(651, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqdestroy___OOZsrcZnimtraZmigrations_u6346(b_1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__OOZsrcZnimtraZmigrations_u9565)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* a_p0, NI a_p0Len_0, tyTuple__QeWl6B6ffS4pU6WWrtcrDw* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__TNYmJG2tqVAKrEI5hlMXCg cmp_p5, tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg order_p6) {
	NI j_1;
	NI bb_1;
	NI i_1;
	NI k_1;
NIM_BOOL* nimErr_;
	nimfr_("mergeAlt", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(335, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");	{
		NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_27;
		NI T3_;
		NI T4_;
		if (m_p3 < 0 || m_p3 >= a_p0Len_0){ raiseIndexError2(m_p3,a_p0Len_0-1); goto BeforeRet_;
		}
		if (nimAddInt(m_p3, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_27)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_27) < 0 || (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_27) >= a_p0Len_0){ raiseIndexError2((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_27),a_p0Len_0-1); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = cmp_p5.ClE_0? cmp_p5.ClP_0(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_27)], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_28)(cmp_p5.ClP_0))(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_27)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T4_ = (NI)0;
		T4_ = star___pureZalgorithm_u8(T3_, order_p6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T4_ <= ((NI)0))) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(336);	j_1 = lo_p2;
	nimln_(338);	{
		if (!!((j_1 <= m_p3))) goto LA9_;
		failedAssertImpl__stdZassertions_u95(TM__JdC9c6SaUkvO1XjYuWP1JWQ_29);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	nimln_(340);	bb_1 = ((NI)0);
	{
		nimln_(341);		while (1) {
			tyTuple__QeWl6B6ffS4pU6WWrtcrDw T13_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_30;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_31;
			if (!(j_1 <= m_p3)) goto LA12;
			nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (bb_1 < 0 || bb_1 >= b_p1Len_0){ raiseIndexError2(bb_1,b_p1Len_0-1); goto BeforeRet_;
			}
			nimlf_(323, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");			if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
			}
			T13_ = a_p0[j_1];
			eqwasMoved___OOZsrcZnimtraZmigrations_u7239((&a_p0[j_1]));
			nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			eqsink___OOZsrcZnimtraZmigrations_u7251((&b_p1[bb_1]), T13_);
			nimlf_(343, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");			if (nimAddInt(bb_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_30)) { raiseOverflow(); goto BeforeRet_;
			};
			bb_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_30);
			nimln_(344);			if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_31)) { raiseOverflow(); goto BeforeRet_;
			};
			j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_31);
		} LA12: ;
	}
	nimln_(348);	i_1 = ((NI)0);
	nimln_(349);	k_1 = lo_p2;
	{
		nimln_(351);		while (1) {
			NIM_BOOL T16_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_35;
			T16_ = (NIM_BOOL)0;
			T16_ = (k_1 < j_1);
			if (!(T16_)) goto LA17_;
			T16_ = (j_1 <= hi_p4);
LA17_: ;
			if (!T16_) goto LA15;
			nimln_(352);			{
				NI T20_;
				NI T21_;
				tyTuple__QeWl6B6ffS4pU6WWrtcrDw T24_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_33;
				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				T20_ = (NI)0;
				T20_ = cmp_p5.ClE_0? cmp_p5.ClP_0(b_p1[i_1], a_p0[j_1], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_32)(cmp_p5.ClP_0))(b_p1[i_1], a_p0[j_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T21_ = (NI)0;
				T21_ = star___pureZalgorithm_u8(T20_, order_p6);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T21_ <= ((NI)0))) goto LA22_;
				nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				nimlf_(323, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				T24_ = b_p1[i_1];
				eqwasMoved___OOZsrcZnimtraZmigrations_u7239((&b_p1[i_1]));
				nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqsink___OOZsrcZnimtraZmigrations_u7251((&a_p0[k_1]), T24_);
				nimlf_(354, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");				if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_33)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_33);
			}
			goto LA18_;
LA22_: ;
			{
				tyTuple__QeWl6B6ffS4pU6WWrtcrDw T26_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_34;
				nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				nimlf_(323, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				T26_ = a_p0[j_1];
				eqwasMoved___OOZsrcZnimtraZmigrations_u7239((&a_p0[j_1]));
				nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				eqsink___OOZsrcZnimtraZmigrations_u7251((&a_p0[k_1]), T26_);
				nimlf_(357, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");				if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_34)) { raiseOverflow(); goto BeforeRet_;
				};
				j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_34);
			}
LA18_: ;
			nimln_(358);			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_35)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_35);
		} LA15: ;
	}
	{
		nimln_(361);		while (1) {
			tyTuple__QeWl6B6ffS4pU6WWrtcrDw T29_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_36;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_37;
			if (!(k_1 < j_1)) goto LA28;
			nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
			}
			nimlf_(323, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");			if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
			}
			T29_ = b_p1[i_1];
			eqwasMoved___OOZsrcZnimtraZmigrations_u7239((&b_p1[i_1]));
			nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");			eqsink___OOZsrcZnimtraZmigrations_u7251((&a_p0[k_1]), T29_);
			nimlf_(363, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_36)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_36);
			nimln_(364);			if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_37)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_37);
		} LA28: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, sort__OOZsrcZnimtraZmigrations_u9529)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* a_p0, NI a_p0Len_0, tyProc__TNYmJG2tqVAKrEI5hlMXCg cmp_p1, tyEnum_SortOrder__sN8D4loGx4Vy9alQGFJGoVg order_p2) {
	tySequence__4eRCaZmrYLLw2k30GPTiMw b_1;
	NI n_1;
	NI s_1;
NIM_BOOL* nimErr_;
	nimfr_("sort", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/algorithm.nim");
{nimErr_ = nimErrorFlag();
	b_1.len = 0; b_1.p = NIM_NIL;
	nimln_(411);	n_1 = a_p0Len_0;
	nimln_(412);	if (((NI)((n_1) / (((NI)2)))) < ((NI)0) || ((NI)((n_1) / (((NI)2)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((n_1) / (((NI)2))), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	b_1 = newSeq__OOZsrcZnimtraZmigrations_u7830(((NI)((n_1) / (((NI)2)))));
	nimln_(413);	s_1 = ((NI)1);
	{
		nimln_(414);		while (1) {
			NI m_1;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_25;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_26;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_43;
			if (!(s_1 < n_1)) goto LA2;
			nimln_(415);			if (nimSubInt(n_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_25)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimSubInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_25), s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_26)) { raiseOverflow(); goto BeforeRet_;
			};
			m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_26);
			{
				nimln_(416);				while (1) {
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_38;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_39;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_40;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_41;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_42;
					if (!(((NI)0) <= m_1)) goto LA4;
					nimln_(417);					if (nimSubInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_38)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_38), ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_39)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_40)) { raiseOverflow(); goto BeforeRet_;
					};
					mergeAlt__OOZsrcZnimtraZmigrations_u9565(a_p0, a_p0Len_0, ((b_1).p) ? (b_1.p->data) : NIM_NIL, b_1.len, (((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_39) >= ((NI)0)) ? (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_39) : ((NI)0)), m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_40), cmp_p1, order_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(418);					if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_41)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt(m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_41), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_42)) { raiseOverflow(); goto BeforeRet_;
					};
					m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_42);
				} LA4: ;
			}
			nimln_(419);			if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_43)) { raiseOverflow(); goto BeforeRet_;
			};
			s_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_43);
		} LA2: ;
	}
	nimlf_(934, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqdestroy___OOZsrcZnimtraZmigrations_u7176(b_1);
	}BeforeRet_: ;
	popFrame();
}
