/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <sys/socket.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE NIM_CONST int osInvalidSocket__pureZnativesockets_u48 = ((int)-1);
N_LIB_PRIVATE int nativeAfInet__pureZnativesockets_u49;
N_LIB_PRIVATE int nativeAfInet6__pureZnativesockets_u50;
N_LIB_PRIVATE int nativeAfUnix__pureZnativesockets_u51;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, atpnativesocketsdotnim_Init000)(void) {
{
	nimfr_("nativesockets", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/nativesockets.nim");
	nimlf_(120, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/nativesockets.nim");	nativeAfInet__pureZnativesockets_u49 = AF_INET;
	nimln_(121);	nativeAfInet6__pureZnativesockets_u50 = AF_INET6;
	nimln_(122);	nativeAfUnix__pureZnativesockets_u51 = AF_UNIX;
	nimTestErrorFlag();
	popFrame();
}
}

