/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__mGPxctZWGqgqUCCIeok9ccg tySequence__mGPxctZWGqgqUCCIeok9ccg;
typedef struct tySequence__mGPxctZWGqgqUCCIeok9ccg_Content tySequence__mGPxctZWGqgqUCCIeok9ccg_Content;
typedef struct tySequence__OaHwijEm2KHEod7LMrnNzA tySequence__OaHwijEm2KHEod7LMrnNzA;
typedef struct tySequence__OaHwijEm2KHEod7LMrnNzA_Content tySequence__OaHwijEm2KHEod7LMrnNzA_Content;
typedef struct tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q;
typedef struct tySequence__FkvojUQdPjfk5uWBVYh8ng tySequence__FkvojUQdPjfk5uWBVYh8ng;
typedef struct tySequence__FkvojUQdPjfk5uWBVYh8ng_Content tySequence__FkvojUQdPjfk5uWBVYh8ng_Content;
typedef struct tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ;
typedef struct tyObject_Option__PIf21JqAO9ck9bbGJvgpfL0Q tyObject_Option__PIf21JqAO9ck9bbGJvgpfL0Q;
typedef struct tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw;
typedef struct tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__hQIfAYFnNr44cTZfDXJxLQ tySequence__hQIfAYFnNr44cTZfDXJxLQ;
typedef struct tySequence__hQIfAYFnNr44cTZfDXJxLQ_Content tySequence__hQIfAYFnNr44cTZfDXJxLQ_Content;
typedef struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyTuple__732F4NLvyCWp6BvEC0QQAg tyTuple__732F4NLvyCWp6BvEC0QQAg;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct tySequence__mGPxctZWGqgqUCCIeok9ccg {
  NI len; tySequence__mGPxctZWGqgqUCCIeok9ccg_Content* p;
};
struct tySequence__OaHwijEm2KHEod7LMrnNzA {
  NI len; tySequence__OaHwijEm2KHEod7LMrnNzA_Content* p;
};
struct tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q {
	tySequence__OaHwijEm2KHEod7LMrnNzA data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__FkvojUQdPjfk5uWBVYh8ng {
  NI len; tySequence__FkvojUQdPjfk5uWBVYh8ng_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ {
	NimStringV2 name;
	NimStringV2 decltype_0;
};
struct tyObject_Option__PIf21JqAO9ck9bbGJvgpfL0Q {
	NI64 val;
	NIM_BOOL has;
};
struct tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ {
	tySequence__FkvojUQdPjfk5uWBVYh8ng columns;
	tySequence__mGPxctZWGqgqUCCIeok9ccg rows;
	NI affectedRowCount;
	tyObject_Option__PIf21JqAO9ck9bbGJvgpfL0Q lastInsertRowId;
};
struct tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw {
	NI len;
	void* p;
};
typedef NU8 tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw {
	tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw kind;
union{
	struct {
	NI64 intValue;
} _kind_2;
	struct {
	NF floatValue;
} _kind_3;
	struct {
	NimStringV2 textValue;
} _kind_4;
	struct {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blobValue;
} _kind_5;
};
};
struct tySequence__hQIfAYFnNr44cTZfDXJxLQ {
  NI len; tySequence__hQIfAYFnNr44cTZfDXJxLQ_Content* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tySequence__mGPxctZWGqgqUCCIeok9ccg_Content { NI cap; tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q data[SEQ_DECL_SIZE]; };
struct tyTuple__732F4NLvyCWp6BvEC0QQAg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw Field3;
};
struct tySequence__OaHwijEm2KHEod7LMrnNzA_Content { NI cap; tyTuple__732F4NLvyCWp6BvEC0QQAg data[SEQ_DECL_SIZE]; };
struct tySequence__FkvojUQdPjfk5uWBVYh8ng_Content { NI cap; tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__hQIfAYFnNr44cTZfDXJxLQ_Content { NI cap; tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u293)(tySequence__OaHwijEm2KHEod7LMrnNzA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u122)(tySequence__FkvojUQdPjfk5uWBVYh8ng dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u272)(tySequence__mGPxctZWGqgqUCCIeok9ccg dest_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tySequence__FkvojUQdPjfk5uWBVYh8ng, eqdup___OOZsrcZnimtraZdriverZbase_u128)(tySequence__FkvojUQdPjfk5uWBVYh8ng src_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__OOZsrcZnimtraZdriverZbase_u143)(tySequence__FkvojUQdPjfk5uWBVYh8ng* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__mGPxctZWGqgqUCCIeok9ccg, eqdup___OOZsrcZnimtraZdriverZbase_u278)(tySequence__mGPxctZWGqgqUCCIeok9ccg src_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__OOZsrcZnimtraZdriverZbase_u500)(tySequence__mGPxctZWGqgqUCCIeok9ccg* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__OaHwijEm2KHEod7LMrnNzA, eqdup___OOZsrcZnimtraZdriverZbase_u299)(tySequence__OaHwijEm2KHEod7LMrnNzA src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdriverZbase_u125)(tySequence__FkvojUQdPjfk5uWBVYh8ng* dest_p0, tySequence__FkvojUQdPjfk5uWBVYh8ng src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdriverZbase_u275)(tySequence__mGPxctZWGqgqUCCIeok9ccg* dest_p0, tySequence__mGPxctZWGqgqUCCIeok9ccg src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdriverZbase_u296)(tySequence__OaHwijEm2KHEod7LMrnNzA* dest_p0, tySequence__OaHwijEm2KHEod7LMrnNzA src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, eqdup___pureZtimes_u2645)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZsrcZnimtraZvalues_u18)(tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u34)(NI64 xX60gensym4__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_u4833)(NF x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2639)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_2 = { 70 | NIM_STRLIT_FLAG, "field \'textValue\' is not accessible for type \'SqlValue\' using \'kind = " };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_3 = {70, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_2};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_4 = { 6 | NIM_STRLIT_FLAG, "svNull" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_5 = {6, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_6 = { 9 | NIM_STRLIT_FLAG, "svInteger" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_7 = {9, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_6};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_8 = { 7 | NIM_STRLIT_FLAG, "svFloat" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_9 = {7, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_8};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_10 = { 6 | NIM_STRLIT_FLAG, "svText" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_11 = {6, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_10};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_12 = { 6 | NIM_STRLIT_FLAG, "svBlob" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_13 = {6, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_12};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_14 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_15 = {0, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_14};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_16 = { 69 | NIM_STRLIT_FLAG, "field \'intValue\' is not accessible for type \'SqlValue\' using \'kind = " };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_17 = {69, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_16};
static const struct {
  NI cap; NIM_CHAR data[71+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_18 = { 71 | NIM_STRLIT_FLAG, "field \'floatValue\' is not accessible for type \'SqlValue\' using \'kind = " };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_19 = {71, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_18};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_20 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_21 = {0, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_20};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_22 = { 6 | NIM_STRLIT_FLAG, "<blob>" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_23 = {6, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_22};
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_24 = {69, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_16};
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_25 = {71, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_18};
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_26 = {70, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_2};
extern TNimTypeV2 NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_;
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__SnSBAx8GC9bY7X6uzL9asswg_27 = { 23 | NIM_STRLIT_FLAG, "SqlValue is not numeric" };
static const NimStringV2 TM__SnSBAx8GC9bY7X6uzL9asswg_28 = {23, (NimStrPayload*)&TM__SnSBAx8GC9bY7X6uzL9asswg_27};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u272)(tySequence__mGPxctZWGqgqUCCIeok9ccg dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			eqdestroy___OOZsrcZnimtraZdriverZbase_u293(dest_p0.p->data[colontmp_].data);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u122)(tySequence__FkvojUQdPjfk5uWBVYh8ng dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].decltype_0.p && !(dest_p0.p->data[colontmp_].decltype_0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].decltype_0.p);
}
			if (dest_p0.p->data[colontmp_].name.p && !(dest_p0.p->data[colontmp_].name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].name.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZnimtraZdriverZbase_u693)(tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ* dest_p0, tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ* src_p1) {
	if ((*dest_p0).columns.p != (*src_p1).columns.p) {	eqdestroy___OOZsrcZnimtraZdriverZbase_u122((*dest_p0).columns);
	}
(*dest_p0).columns.len = (*src_p1).columns.len; (*dest_p0).columns.p = (*src_p1).columns.p;
	if ((*dest_p0).rows.p != (*src_p1).rows.p) {	eqdestroy___OOZsrcZnimtraZdriverZbase_u272((*dest_p0).rows);
	}
(*dest_p0).rows.len = (*src_p1).rows.len; (*dest_p0).rows.p = (*src_p1).rows.p;
	(*dest_p0).affectedRowCount = (*src_p1).affectedRowCount;
	(*dest_p0).lastInsertRowId.val = (*src_p1).lastInsertRowId.val;
	(*dest_p0).lastInsertRowId.has = (*src_p1).lastInsertRowId.has;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZdriverZbase_u681)(tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ* dest_p0) {
	(*dest_p0).columns.len = 0; (*dest_p0).columns.p = NIM_NIL;
	(*dest_p0).rows.len = 0; (*dest_p0).rows.p = NIM_NIL;
	(*dest_p0).affectedRowCount = 0;
	(*dest_p0).lastInsertRowId.val = 0;
	(*dest_p0).lastInsertRowId.has = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u684)(tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ* dest_p0) {
	eqdestroy___OOZsrcZnimtraZdriverZbase_u272((*dest_p0).rows);
	eqdestroy___OOZsrcZnimtraZdriverZbase_u122((*dest_p0).columns);
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u188)(tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ* dest_p0) {
	if ((*dest_p0).decltype_0.p && !((*dest_p0).decltype_0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).decltype_0.p);
}
	if ((*dest_p0).name.p && !((*dest_p0).name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).name.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZdriverZbase_u185)(tyObject_SqlColumn__PrHzcJVf2mU9abT54rGpOCQ* dest_p0) {
	(*dest_p0).name.len = 0; (*dest_p0).name.p = NIM_NIL;
	(*dest_p0).decltype_0.len = 0; (*dest_p0).decltype_0.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__FkvojUQdPjfk5uWBVYh8ng, eqdup___OOZsrcZnimtraZdriverZbase_u128)(tySequence__FkvojUQdPjfk5uWBVYh8ng src_p0) {
	tySequence__FkvojUQdPjfk5uWBVYh8ng result;
	NI T1_;
	NI colontmp_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__OOZsrcZnimtraZdriverZbase_u143((&result), T1_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T4_;
			T4_ = result.len;
			if (!(colontmp_ < T4_)) goto LA3;
			result.p->data[colontmp_].name = eqdup___system_u2728(src_p0.p->data[colontmp_].name);
			result.p->data[colontmp_].decltype_0 = eqdup___system_u2728(src_p0.p->data[colontmp_].decltype_0);
			colontmp_ += ((NI)1);
		} LA3: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__mGPxctZWGqgqUCCIeok9ccg, eqdup___OOZsrcZnimtraZdriverZbase_u278)(tySequence__mGPxctZWGqgqUCCIeok9ccg src_p0) {
	tySequence__mGPxctZWGqgqUCCIeok9ccg result;
	NI T1_;
	NI colontmp_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__OOZsrcZnimtraZdriverZbase_u500((&result), T1_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T4_;
			T4_ = result.len;
			if (!(colontmp_ < T4_)) goto LA3;
			result.p->data[colontmp_].data = eqdup___OOZsrcZnimtraZdriverZbase_u299(src_p0.p->data[colontmp_].data);
			result.p->data[colontmp_].counter = src_p0.p->data[colontmp_].counter;
			result.p->data[colontmp_].first = src_p0.p->data[colontmp_].first;
			result.p->data[colontmp_].last = src_p0.p->data[colontmp_].last;
			colontmp_ += ((NI)1);
		} LA3: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdup___OOZsrcZnimtraZdriverZbase_u690)(tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ* src_p0, tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ* Result) {
	nimZeroMem((void*)Result, sizeof(tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ));
	(*Result).columns = eqdup___OOZsrcZnimtraZdriverZbase_u128((*src_p0).columns);
	(*Result).rows = eqdup___OOZsrcZnimtraZdriverZbase_u278((*src_p0).rows);
	(*Result).affectedRowCount = (*src_p0).affectedRowCount;
	(*Result).lastInsertRowId.val = (*src_p0).lastInsertRowId.val;
	(*Result).lastInsertRowId.has = (*src_p0).lastInsertRowId.has;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw*) (x_p0))).p == (*((tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdriverZbase_u125)(tySequence__FkvojUQdPjfk5uWBVYh8ng* dest_p0, tySequence__FkvojUQdPjfk5uWBVYh8ng src_p1) {
	NI T6_;
	NI colontmp_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__OOZsrcZnimtraZdriverZbase_u143((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			eqcopy___system_u2725((&(*dest_p0).p->data[colontmp_].name), src_p1.p->data[colontmp_].name);
			eqcopy___system_u2725((&(*dest_p0).p->data[colontmp_].decltype_0), src_p1.p->data[colontmp_].decltype_0);
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdriverZbase_u275)(tySequence__mGPxctZWGqgqUCCIeok9ccg* dest_p0, tySequence__mGPxctZWGqgqUCCIeok9ccg src_p1) {
	NI T6_;
	NI colontmp_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__OOZsrcZnimtraZdriverZbase_u500((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			eqcopy___OOZsrcZnimtraZdriverZbase_u296((&(*dest_p0).p->data[colontmp_].data), src_p1.p->data[colontmp_].data);
			(*dest_p0).p->data[colontmp_].counter = src_p1.p->data[colontmp_].counter;
			(*dest_p0).p->data[colontmp_].first = src_p1.p->data[colontmp_].first;
			(*dest_p0).p->data[colontmp_].last = src_p1.p->data[colontmp_].last;
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdriverZbase_u687)(tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ* dest_p0, tyObject_SqlResult__XgExlkHlXkvMo3OTLm9b9cfQ* src_p1) {
	eqcopy___OOZsrcZnimtraZdriverZbase_u125((&(*dest_p0).columns), (*src_p1).columns);
	eqcopy___OOZsrcZnimtraZdriverZbase_u275((&(*dest_p0).rows), (*src_p1).rows);
	(*dest_p0).affectedRowCount = (*src_p1).affectedRowCount;
	(*dest_p0).lastInsertRowId.val = (*src_p1).lastInsertRowId.val;
	(*dest_p0).lastInsertRowId.has = (*src_p1).lastInsertRowId.has;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw, eqdup___OOZsrcZnimtraZvalues_u79)(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw src_p0) {
	tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw));
	result.kind = src_p0.kind;
	switch (result.kind) {
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
	{
		result._kind_2.intValue = src_p0._kind_2.intValue;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
	{
		result._kind_3.floatValue = src_p0._kind_3.floatValue;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
	{
		result._kind_4.textValue = eqdup___system_u2728(src_p0._kind_4.textValue);
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
	{
		result._kind_5.blobValue = eqdup___pureZtimes_u2645(src_p0._kind_5.blobValue);
	}
	break;
	default: __builtin_unreachable();
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZsrcZnimtraZvalues_u18)(tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
	{
		result = TM__SnSBAx8GC9bY7X6uzL9asswg_5;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
	{
		result = TM__SnSBAx8GC9bY7X6uzL9asswg_7;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
	{
		result = TM__SnSBAx8GC9bY7X6uzL9asswg_9;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
	{
		result = TM__SnSBAx8GC9bY7X6uzL9asswg_11;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
	{
		result = TM__SnSBAx8GC9bY7X6uzL9asswg_13;
	}
	break;
	default:
	{
		result = TM__SnSBAx8GC9bY7X6uzL9asswg_15;
	}
	break;
	}
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, asString__OOZsrcZnimtraZvalues_u253)(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw value_p0) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("asString", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/values.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(114, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/values.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	switch (value_p0.kind) {
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
	{
		nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (!(((8 &((NU8)1<<((NU)((value_p0.kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__SnSBAx8GC9bY7X6uzL9asswg_3, dollar___OOZsrcZnimtraZvalues_u18(value_p0.kind)); goto BeforeRet_;
		}
		eqcopy___system_u2725((&result), value_p0._kind_4.textValue);
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
	{
		nimlf_(113, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/values.nim");		nimln_(118);		if (!(((2 &((NU8)1<<((NU)((value_p0.kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__SnSBAx8GC9bY7X6uzL9asswg_17, dollar___OOZsrcZnimtraZvalues_u18(value_p0.kind)); goto BeforeRet_;
		}
		result = dollar___systemZdollars_u34(value_p0._kind_2.intValue);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
	{
		nimln_(113);		nimln_(120);		if (!(((4 &((NU8)1<<((NU)((value_p0.kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__SnSBAx8GC9bY7X6uzL9asswg_19, dollar___OOZsrcZnimtraZvalues_u18(value_p0.kind)); goto BeforeRet_;
		}
		result = dollar___system_u4833(value_p0._kind_3.floatValue);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
	{
		nimln_(113);		nimln_(122);		result = TM__SnSBAx8GC9bY7X6uzL9asswg_21;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
	{
		nimln_(113);		nimln_(124);		result = TM__SnSBAx8GC9bY7X6uzL9asswg_23;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw, toSqlValue__OOZsrcZnimtraZvalues_u119)(NimStringV2 value_p0) {
	tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw result;
	NimStringV2 colontmpD_;
	nimfr_("toSqlValue", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/values.nim");
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(57);	result.kind = ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3);
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	colontmpD_ = eqdup___system_u2728(value_p0);
	result._kind_4.textValue = colontmpD_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZvalues_u73)(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
	{
		if ((*dest_p0)._kind_4.textValue.p && !((*dest_p0)._kind_4.textValue.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_4.textValue.p);
}
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
	{
		eqdestroy___pureZtimes_u2639((*dest_p0)._kind_5.blobValue);
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u190)(tySequence__hQIfAYFnNr44cTZfDXJxLQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			switch (dest_p0.p->data[colontmp_].kind) {
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
			{
				if (dest_p0.p->data[colontmp_]._kind_4.textValue.p && !(dest_p0.p->data[colontmp_]._kind_4.textValue.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_]._kind_4.textValue.p);
}
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
			{
				eqdestroy___pureZtimes_u2639(dest_p0.p->data[colontmp_]._kind_5.blobValue);
			}
			break;
			default: __builtin_unreachable();
			}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw));
}
}
N_LIB_PRIVATE N_NIMCALL(NI64, asInt64__OOZsrcZnimtraZvalues_u249)(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw value_p0) {
	NI64 result;
	NI64 colontmpD_;
	NI64 colontmpD__2;
	NI64 colontmpD__3;
NIM_BOOL* nimErr_;
	nimfr_("asInt64", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/values.nim");
{nimErr_ = nimErrorFlag();
	result = (NI64)0;
	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI64)0;
	colontmpD__3 = (NI64)0;
	nimlf_(103, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/values.nim");	switch (value_p0.kind) {
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
	{
		nimln_(105);		if (!(((2 &((NU8)1<<((NU)((value_p0.kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__SnSBAx8GC9bY7X6uzL9asswg_24, dollar___OOZsrcZnimtraZvalues_u18(value_p0.kind)); goto BeforeRet_;
		}
		colontmpD_ = value_p0._kind_2.intValue;
		result = colontmpD_;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
	{
		nimln_(107);		if (!(((4 &((NU8)1<<((NU)((value_p0.kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__SnSBAx8GC9bY7X6uzL9asswg_25, dollar___OOZsrcZnimtraZvalues_u18(value_p0.kind)); goto BeforeRet_;
		}
		if ((((NI64) (value_p0._kind_3.floatValue))) < (IL64(-9223372036854775807) - IL64(1)) || (((NI64) (value_p0._kind_3.floatValue))) > IL64(9223372036854775807)){ raiseRangeErrorI(((NI64) (value_p0._kind_3.floatValue)), (IL64(-9223372036854775807) - IL64(1)), IL64(9223372036854775807)); goto BeforeRet_;
		}
		colontmpD__2 = (((NI64) (value_p0._kind_3.floatValue)));
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
	{
		NI T5_;
		nimln_(109);		if (!(((8 &((NU8)1<<((NU)((value_p0.kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__SnSBAx8GC9bY7X6uzL9asswg_26, dollar___OOZsrcZnimtraZvalues_u18(value_p0.kind)); goto LA4_;
		}
		T5_ = (NI)0;
		T5_ = nsuParseInt(value_p0._kind_4.textValue);
		if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		colontmpD__3 = ((NI64) (T5_));
		result = colontmpD__3;
		{
			LA4_:;
		}
		{
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* T9_;
		T9_ = NIM_NIL;
		T9_ = (tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ*) nimNewObj(sizeof(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ), NIM_ALIGNOF(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ));
		(*T9_).Sup.Sup.Sup.m_type = (&NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_);
		(*T9_).Sup.Sup.name = "ValueError";
		(*T9_).Sup.Sup.message = TM__SnSBAx8GC9bY7X6uzL9asswg_28;
		(*T9_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(111);		raiseExceptionEx((Exception*)T9_, "ValueError", "asInt64", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/values.nim", 111);
goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
