/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw;
typedef struct tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA;
typedef struct tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
typedef NU8 tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w;
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
struct tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA {
	RootObj Sup;
};
struct tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw {
	tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA Sup;
};
struct tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA {
	tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA Sup;
};
struct tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ {
	tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA Sup;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u16)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u83)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, NimStringV2 ident_p1);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u90)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u312)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u315)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0, NimStringV2 ident_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u319)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u322)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u325)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0, NimStringV2 ident_p1);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u329)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u332)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u335)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0, NimStringV2 ident_p1);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u339)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3520)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
extern TNimTypeV2 NTIv2__d1kCVVj9aY0lUORd5Dpjkdg_;
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_2 = { 26 | NIM_STRLIT_FLAG, "name() must be implemented" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_3 = {26, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_2};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_4 = { 32 | NIM_STRLIT_FLAG, "quoteIdent() must be implemented" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_5 = {32, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_6 = { 6 | NIM_STRLIT_FLAG, "sqlite" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_7 = {6, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_8 = { 1 | NIM_STRLIT_FLAG, "\"" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_9 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_8};
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_10 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_8};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_11 = { 2 | NIM_STRLIT_FLAG, "\"\"" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_12 = {2, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_11};
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_13 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_8};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_14 = { 8 | NIM_STRLIT_FLAG, "postgres" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_15 = {8, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_14};
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_16 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_8};
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_17 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_8};
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_18 = {2, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_11};
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_19 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_8};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_20 = { 5 | NIM_STRLIT_FLAG, "mysql" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_21 = {5, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_20};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_22 = { 1 | NIM_STRLIT_FLAG, "`" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_23 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_22};
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_24 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_22};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__u0iT39bwLJrVrSM08h0X4ow_25 = { 2 | NIM_STRLIT_FLAG, "``" };
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_26 = {2, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_25};
static const NimStringV2 TM__u0iT39bwLJrVrSM08h0X4ow_27 = {1, (NimStrPayload*)&TM__u0iT39bwLJrVrSM08h0X4ow_22};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u16)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0) {
	NimStringV2 result;
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg* T1_;
	nimfr_("name", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
{	result.len = 0; result.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg*) nimNewObj(sizeof(tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg), NIM_ALIGNOF(tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg));
	(*T1_).Sup.Sup.m_type = (&NTIv2__d1kCVVj9aY0lUORd5Dpjkdg_);
	(*T1_).Sup.name = "CatchableError";
	(*T1_).Sup.message = TM__u0iT39bwLJrVrSM08h0X4ow_3;
	(*T1_).Sup.parent = ((Exception*) NIM_NIL);
	nimlf_(15, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");	raiseExceptionEx((Exception*)T1_, "CatchableError", "name", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim", 15);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u83)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, NimStringV2 ident_p1) {
	NimStringV2 result;
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg* T1_;
	nimfr_("quoteIdent", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
{	result.len = 0; result.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg*) nimNewObj(sizeof(tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg), NIM_ALIGNOF(tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg));
	(*T1_).Sup.Sup.m_type = (&NTIv2__d1kCVVj9aY0lUORd5Dpjkdg_);
	(*T1_).Sup.name = "CatchableError";
	(*T1_).Sup.message = TM__u0iT39bwLJrVrSM08h0X4ow_5;
	(*T1_).Sup.parent = ((Exception*) NIM_NIL);
	nimln_(18);	raiseExceptionEx((Exception*)T1_, "CatchableError", "quoteIdent", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim", 18);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u90)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0) {
	tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w result;
	nimfr_("placeholderStyle", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
	nimln_(21);	result = ((tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w)0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u312)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0) {
	NimStringV2 result;
	nimfr_("name", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
	nimln_(33);	result = TM__u0iT39bwLJrVrSM08h0X4ow_7;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u315)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0, NimStringV2 ident_p1) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("quoteIdent", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(36);	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nsuReplaceStr(ident_p1, TM__u0iT39bwLJrVrSM08h0X4ow_10, TM__u0iT39bwLJrVrSM08h0X4ow_12);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(colontmpD_.len + 2);
appendString((&T1_), TM__u0iT39bwLJrVrSM08h0X4ow_9);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__u0iT39bwLJrVrSM08h0X4ow_13);
	result = T1_;
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u319)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0) {
	tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w result;
	nimfr_("placeholderStyle", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
	nimlf_(39, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");	result = ((tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w)0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u322)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0) {
	NimStringV2 result;
	nimfr_("name", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
	nimln_(42);	result = TM__u0iT39bwLJrVrSM08h0X4ow_15;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u325)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0, NimStringV2 ident_p1) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("quoteIdent", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(45);	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nsuReplaceStr(ident_p1, TM__u0iT39bwLJrVrSM08h0X4ow_17, TM__u0iT39bwLJrVrSM08h0X4ow_18);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(colontmpD_.len + 2);
appendString((&T1_), TM__u0iT39bwLJrVrSM08h0X4ow_16);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__u0iT39bwLJrVrSM08h0X4ow_19);
	result = T1_;
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u329)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0) {
	tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w result;
	nimfr_("placeholderStyle", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
	nimlf_(48, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");	result = ((tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w)1);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, name__OOZsrcZnimtraZdialects_u332)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0) {
	NimStringV2 result;
	nimfr_("name", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
	nimln_(51);	result = TM__u0iT39bwLJrVrSM08h0X4ow_21;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u335)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0, NimStringV2 ident_p1) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("quoteIdent", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(54);	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nsuReplaceStr(ident_p1, TM__u0iT39bwLJrVrSM08h0X4ow_24, TM__u0iT39bwLJrVrSM08h0X4ow_26);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(colontmpD_.len + 2);
appendString((&T1_), TM__u0iT39bwLJrVrSM08h0X4ow_23);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__u0iT39bwLJrVrSM08h0X4ow_27);
	result = T1_;
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w, placeholderStyle__OOZsrcZnimtraZdialects_u339)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0) {
	tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w result;
	nimfr_("placeholderStyle", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");
	nimlf_(57, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/dialects.nim");	result = ((tyEnum_PlaceholderStyle__D4IQHv9c4ydQl9aBWgBVS74w)0);
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimln_(360);	nimln_(364);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* h_1;
	NI T1_;
	nimfr_("nimIncRefCyclic", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(47, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	h_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T1_));
	nimlf_(48, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
	popFrame();
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimlf_(521, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3520(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdialects_u146)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw** dest_p0, tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdialects_u244)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA** dest_p0, tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdialects_u294)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ** dest_p0, tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
