/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA;
typedef struct tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw;
typedef struct tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ;
typedef struct tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw;
typedef struct tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw;
typedef struct tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw;
typedef struct tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA;
typedef struct tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ {
	NI val;
	NIM_BOOL has;
};
struct tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw {
	NimStringV2 val;
	NIM_BOOL has;
};
struct tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw {
	NimStringV2 name;
	NimStringV2 nimType;
	NimStringV2 dbType;
	NIM_BOOL primary;
	NIM_BOOL autoincrement;
	NIM_BOOL unique;
	NIM_BOOL indexed;
	tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ maxLength;
	tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw defaultValue;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag {
	Exception Sup;
};
struct tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NimStringV2 tyArray__A2YC0h9cZydgH7zGAndH9bLg[6];
struct tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA {
	RootObj Sup;
};
struct tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw {
	tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA Sup;
};
struct tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA {
	tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA Sup;
};
struct tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ {
	tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA Sup;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u55)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteIdent__OOZsrcZnimtraZdialects_u88)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, NimStringV2 ident_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(NIM_BOOL, isSome__pureZtimes_u4162)(tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ self_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static N_INLINE(NI*, get__pureZtimes_u4246)(tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ* self_p0);
static N_INLINE(NIM_BOOL, isNone__pureZtimes_u4232)(tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ self_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderDefaultClause__OOZsrcZnimtraZschema_u23)(tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p0);
static N_INLINE(NIM_BOOL, isNone__OOZsrcZnimtraZschema_u29)(tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw self_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
static N_INLINE(NimStringV2*, get__OOZsrcZnimtraZschema_u43)(tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw* self_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, looksLikeSqlExpression__OOZsrcZnimtraZschema_u11)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToUpperAsciiStr)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, contains__stdZenumutils_u50)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
static N_INLINE(NI, find__stdZenumutils_u55)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_CHAR, X5BX5D___system_u8541)(NimStringV2 s_p0, NI i_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, allCharsInSet__pureZstrutils_u1569)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw theSet_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, sqlStringLiteral__OOZsrcZnimtraZschema_u8)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u81)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u106)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u131)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_2 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_3 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_2};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_4 = { 12 | NIM_STRLIT_FLAG, " PRIMARY KEY" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_5 = {12, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_6 = { 7 | NIM_STRLIT_FLAG, " UNIQUE" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_7 = {7, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_6};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_8 = { 4 | NIM_STRLIT_FLAG, "TEXT" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_9 = {4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_8};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_10 = { 15 | NIM_STRLIT_FLAG, " CHECK (length(" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_11 = {15, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_10};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_12 = { 5 | NIM_STRLIT_FLAG, ") <= " };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_13 = {5, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_12};
extern TNimTypeV2 NTIv2__VdQkhRirfRSoOEZYCYVm9cw_;
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_14 = { 34 | NIM_STRLIT_FLAG, "Can\'t obtain a value from a `none`" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_15 = {34, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_14};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_16 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_17 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_16};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_18 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_19 = {0, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_18};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_20 = {34, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_14};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__oxxEQmOSnZEGUk8Yy1EXUw_21 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_22 = {0, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_18};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_25 = { 4 | NIM_STRLIT_FLAG, "NULL" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_26 = { 4 | NIM_STRLIT_FLAG, "TRUE" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_27 = { 5 | NIM_STRLIT_FLAG, "FALSE" };
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_28 = { 17 | NIM_STRLIT_FLAG, "CURRENT_TIMESTAMP" };
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_29 = { 12 | NIM_STRLIT_FLAG, "CURRENT_DATE" };
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_30 = { 12 | NIM_STRLIT_FLAG, "CURRENT_TIME" };
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__oxxEQmOSnZEGUk8Yy1EXUw_32 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x68, 0xff, 0x03,
0x20, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_33 = { 9 | NIM_STRLIT_FLAG, " DEFAULT " };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_34 = {9, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_33};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_35 = {9, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_33};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_36 = { 1 | NIM_STRLIT_FLAG, "\'" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_37 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_36};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_38 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_36};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_39 = { 2 | NIM_STRLIT_FLAG, "\'\'" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_40 = {2, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_39};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_41 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_36};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_42 = { 4 | NIM_STRLIT_FLAG, "UUID" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_43 = {4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_42};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_44 = {4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_8};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_45 = { 7 | NIM_STRLIT_FLAG, "INTEGER" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_46 = {7, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_45};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_47 = { 34 | NIM_STRLIT_FLAG, " INTEGER PRIMARY KEY AUTOINCREMENT" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_48 = {34, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_47};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_49 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_2};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_50 = {12, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_4};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_51 = {7, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_6};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_52 = {4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_8};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_53 = {15, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_10};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_54 = {5, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_12};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_55 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_16};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_56 = {7, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_45};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_57 = { 6 | NIM_STRLIT_FLAG, "SERIAL" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_58 = {6, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_57};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_59 = { 8 | NIM_STRLIT_FLAG, "DATETIME" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_60 = {8, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_59};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_61 = { 24 | NIM_STRLIT_FLAG, "TIMESTAMP WITH TIME ZONE" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_62 = {24, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_61};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_63 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_2};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_64 = {12, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_4};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_65 = {7, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_6};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_66 = {4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_8};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_67 = {15, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_10};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_68 = {5, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_12};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_69 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_16};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_70 = {7, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_45};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_71 = { 18 | NIM_STRLIT_FLAG, "INT AUTO_INCREMENT" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_72 = {18, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_71};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_73 = {4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_42};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_74 = { 8 | NIM_STRLIT_FLAG, "CHAR(36)" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_75 = {8, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_74};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_76 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_2};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_77 = {12, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_4};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_78 = {7, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_6};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_79 = {4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_8};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__oxxEQmOSnZEGUk8Yy1EXUw_80 = { 9 | NIM_STRLIT_FLAG, " VARCHAR(" };
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_81 = {9, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_80};
static const NimStringV2 TM__oxxEQmOSnZEGUk8Yy1EXUw_82 = {1, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_16};
static NIM_CONST tyArray__A2YC0h9cZydgH7zGAndH9bLg TM__oxxEQmOSnZEGUk8Yy1EXUw_24 = {{4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_25},
{4, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_26},
{5, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_27},
{17, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_28},
{12, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_29},
{12, (NimStrPayload*)&TM__oxxEQmOSnZEGUk8Yy1EXUw_30}}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NIM_BOOL, isSome__pureZtimes_u4162)(tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ self_p0) {
	NIM_BOOL result;
	nimfr_("isSome", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim");
	nimlf_(162, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim");	result = self_p0.has;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");
{	nimlf_(33, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isNone__pureZtimes_u4232)(tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ self_p0) {
	NIM_BOOL result;
	nimfr_("isNone", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim");
	nimlf_(177, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim");	nimln_(189);	result = !(self_p0.has);
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
static N_INLINE(NI*, get__pureZtimes_u4246)(tyObject_Option__Fx9cYzUZw5MeI1prAeNV4MQ* self_p0) {
	NI* result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (NI*)0;
	nimln_(202);	{
		NIM_BOOL T3_;
		tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__pureZtimes_u4232((*self_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw*) nimNewObj(sizeof(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw), NIM_ALIGNOF(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__VdQkhRirfRSoOEZYCYVm9cw_);
		(*T6_).Sup.Sup.name = "UnpackDefect";
		(*T6_).Sup.Sup.message = TM__oxxEQmOSnZEGUk8Yy1EXUw_15;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(203);		raiseExceptionEx((Exception*)T6_, "UnpackDefect", "get", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim", 203);
goto BeforeRet_;
	}
LA4_: ;
	nimln_(204);	result = (&(*self_p0).val);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isNone__OOZsrcZnimtraZschema_u29)(tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw self_p0) {
	NIM_BOOL result;
	nimfr_("isNone", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim");
	nimln_(177);	nimln_(189);	result = !(self_p0.has);
	popFrame();
	return result;
}
static N_INLINE(NimStringV2*, get__OOZsrcZnimtraZschema_u43)(tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw* self_p0) {
	NimStringV2* result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (NimStringV2*)0;
	nimln_(202);	{
		NIM_BOOL T3_;
		tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__OOZsrcZnimtraZschema_u29((*self_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw*) nimNewObj(sizeof(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw), NIM_ALIGNOF(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__VdQkhRirfRSoOEZYCYVm9cw_);
		(*T6_).Sup.Sup.name = "UnpackDefect";
		(*T6_).Sup.Sup.message = TM__oxxEQmOSnZEGUk8Yy1EXUw_20;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(203);		raiseExceptionEx((Exception*)T6_, "UnpackDefect", "get", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/options.nim", 203);
goto BeforeRet_;
	}
LA4_: ;
	nimln_(204);	result = (&(*self_p0).val);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, find__stdZenumutils_u55)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NI result;
	nimfr_("find", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
{	nimlf_(1918, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	result = ((NI)0);
	{
		NimStringV2* i_1;
		NI i_2;
		i_1 = (NimStringV2*)0;
		nimlf_(18, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(19);			while (1) {
				NI TM__oxxEQmOSnZEGUk8Yy1EXUw_23;
				if (!(i_2 < a_p0Len_0)) goto LA3;
				nimlf_(1919, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");				if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
				}
				i_1 = (&a_p0[i_2]);
				nimln_(1920);				{
					if (!eqStrings((*i_1), item_p1)) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				nimln_(1921);				if (nimAddInt(result, ((NI)1), &TM__oxxEQmOSnZEGUk8Yy1EXUw_23)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__oxxEQmOSnZEGUk8Yy1EXUw_23);
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(1922, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZenumutils_u50)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
{	nimln_(1936);	nimln_(1924);	nimln_(1936);	T1_ = (NI)0;
	T1_ = find__stdZenumutils_u55(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_CHAR, X5BX5D___system_u8541)(NimStringV2 s_p0, NI i_p1) {
	NIM_CHAR result;
	NI TM__oxxEQmOSnZEGUk8Yy1EXUw_31;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/indices.nim");
{	result = (NIM_CHAR)0;
	if (nimSubInt(s_p0.len, i_p1, &TM__oxxEQmOSnZEGUk8Yy1EXUw_31)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__oxxEQmOSnZEGUk8Yy1EXUw_31) < 0 || (NI)(TM__oxxEQmOSnZEGUk8Yy1EXUw_31) >= s_p0.len){ raiseIndexError2((NI)(TM__oxxEQmOSnZEGUk8Yy1EXUw_31),s_p0.len-1); goto BeforeRet_;
	}
	result = s_p0.p->data[(NI)(TM__oxxEQmOSnZEGUk8Yy1EXUw_31)];
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, looksLikeSqlExpression__OOZsrcZnimtraZschema_u11)(NimStringV2 value_p0) {
	NIM_BOOL result;
	NimStringV2 trimmed_1;
	NimStringV2 upper_1;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw numericChars_1;
NIM_BOOL* nimErr_;
	nimfr_("looksLikeSqlExpression", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	trimmed_1.len = 0; trimmed_1.p = NIM_NIL;
	upper_1.len = 0; upper_1.p = NIM_NIL;
	nimlf_(12, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	{
		if (!(value_p0.len == ((NI)0))) goto LA4_;
		nimln_(13);		nimln_(11);		nimln_(13);		result = NIM_FALSE;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (upper_1.p && !(upper_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(upper_1.p);
}
		if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(15, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	trimmed_1 = nsuStrip(value_p0, NIM_TRUE, NIM_TRUE, TM__oxxEQmOSnZEGUk8Yy1EXUw_21);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(16);	{
		if (!(trimmed_1.len == ((NI)0))) goto LA8_;
		nimln_(17);		nimln_(11);		nimln_(17);		result = NIM_FALSE;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (upper_1.p && !(upper_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(upper_1.p);
}
		if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
		goto BeforeRet_;
	}
LA8_: ;
	nimlf_(19, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	upper_1 = nsuToUpperAsciiStr(trimmed_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(20);	{
		NIM_BOOL T12_;
		T12_ = (NIM_BOOL)0;
		T12_ = contains__stdZenumutils_u50(TM__oxxEQmOSnZEGUk8Yy1EXUw_24, 6, upper_1);
		if (!T12_) goto LA13_;
		nimln_(21);		nimln_(11);		nimln_(21);		result = NIM_TRUE;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (upper_1.p && !(upper_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(upper_1.p);
}
		if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
		goto BeforeRet_;
	}
LA13_: ;
	nimlf_(23, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	{
		NIM_BOOL T17_;
		NIM_CHAR T19_;
		T17_ = (NIM_BOOL)0;
		if (((NI)0) < 0 || ((NI)0) >= trimmed_1.len){ raiseIndexError2(((NI)0),trimmed_1.len-1); goto LA1_;
		}
		T17_ = ((NU8)(trimmed_1.p->data[((NI)0)]) == (NU8)(40));
		if (!(T17_)) goto LA18_;
		T19_ = (NIM_CHAR)0;
		T19_ = X5BX5D___system_u8541(trimmed_1, ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T17_ = ((NU8)(T19_) == (NU8)(41));
LA18_: ;
		if (!T17_) goto LA20_;
		nimln_(24);		nimln_(11);		nimln_(24);		result = NIM_TRUE;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (upper_1.p && !(upper_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(upper_1.p);
}
		if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
		goto BeforeRet_;
	}
LA20_: ;
	nimZeroMem((void*)numericChars_1, sizeof(tySet_tyChar__nmiMWKVIe46vacnhAFrQvw));
	nimlf_(26, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	nimCopyMem((void*)numericChars_1, (NIM_CONST void*)TM__oxxEQmOSnZEGUk8Yy1EXUw_32, 32);
	nimln_(27);	{
		NIM_BOOL T24_;
		T24_ = (NIM_BOOL)0;
		T24_ = allCharsInSet__pureZstrutils_u1569(trimmed_1, numericChars_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T24_) goto LA25_;
		nimln_(28);		nimln_(11);		nimln_(28);		result = NIM_TRUE;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (upper_1.p && !(upper_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(upper_1.p);
}
		if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
		goto BeforeRet_;
	}
LA25_: ;
	result = NIM_FALSE;
	{
		LA1_:;
	}
	{
		if (upper_1.p && !(upper_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(upper_1.p);
}
		if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, sqlStringLiteral__OOZsrcZnimtraZschema_u8)(NimStringV2 value_p0) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("sqlStringLiteral", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(9, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nsuReplaceStr(value_p0, TM__oxxEQmOSnZEGUk8Yy1EXUw_38, TM__oxxEQmOSnZEGUk8Yy1EXUw_40);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(colontmpD_.len + 2);
appendString((&T1_), TM__oxxEQmOSnZEGUk8Yy1EXUw_37);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__oxxEQmOSnZEGUk8Yy1EXUw_41);
	result = T1_;
	nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderDefaultClause__OOZsrcZnimtraZschema_u23)(tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p0) {
	NimStringV2 result;
	NimStringV2 raw_1;
	NimStringV2* T7_;
	NimStringV2 T12_;
NIM_BOOL* nimErr_;
	nimfr_("renderDefaultClause", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	raw_1.len = 0; raw_1.p = NIM_NIL;
	nimlf_(33, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = isNone__OOZsrcZnimtraZschema_u29((*field_p0).defaultValue);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T4_) goto LA5_;
		nimln_(34);		nimln_(32);		nimln_(34);		result = TM__oxxEQmOSnZEGUk8Yy1EXUw_19;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (raw_1.p && !(raw_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(raw_1.p);
}
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(36, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	T7_ = (NimStringV2*)0;
	T7_ = get__OOZsrcZnimtraZschema_u43((&(*field_p0).defaultValue));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	raw_1 = nsuStrip((*T7_), NIM_TRUE, NIM_TRUE, TM__oxxEQmOSnZEGUk8Yy1EXUw_21);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(37);	{
		if (!(raw_1.len == ((NI)0))) goto LA10_;
		nimln_(38);		nimln_(32);		nimln_(38);		result = TM__oxxEQmOSnZEGUk8Yy1EXUw_22;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (raw_1.p && !(raw_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(raw_1.p);
}
		goto BeforeRet_;
	}
LA10_: ;
	T12_.len = 0; T12_.p = NIM_NIL;
	nimlf_(40, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	{
		NIM_BOOL T15_;
		NimStringV2 T18_;
		T15_ = (NIM_BOOL)0;
		T15_ = looksLikeSqlExpression__OOZsrcZnimtraZschema_u11(raw_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T15_) goto LA16_;
		nimln_(32);		nimln_(41);		T18_.len = 0; T18_.p = NIM_NIL;
		T18_ = rawNewString(raw_1.len + 9);
appendString((&T18_), TM__oxxEQmOSnZEGUk8Yy1EXUw_34);
appendString((&T18_), raw_1);
		result = T18_;
	}
	goto LA13_;
LA16_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 T20_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(32);		nimln_(43);		T20_.len = 0; T20_.p = NIM_NIL;
		colontmpD_ = sqlStringLiteral__OOZsrcZnimtraZschema_u8(raw_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T20_ = rawNewString(colontmpD_.len + 9);
appendString((&T20_), TM__oxxEQmOSnZEGUk8Yy1EXUw_35);
appendString((&T20_), colontmpD_);
		result = T20_;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
LA13_: ;
	{
		LA1_:;
	}
	{
		if (raw_1.p && !(raw_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(raw_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u55)(tyObject_DialectcolonObjectType___MamsVEdiFScvk2CtoIgKRA* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2) {
	NimStringV2 result;
	NimStringV2 colName_1;
	NimStringV2 colontmpD_;
	NimStringV2 T2_;
NIM_BOOL* nimErr_;
	nimfr_("columnDefinitionSqlImpl", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colName_1.len = 0; colName_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(46, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	colName_1 = quoteIdent__OOZsrcZnimtraZdialects_u88(dialect_p0, (*field_p1).name);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(47);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(colName_1.len + (*field_p1).dbType.len + 1);
appendString((&T2_), colName_1);
appendString((&T2_), TM__oxxEQmOSnZEGUk8Yy1EXUw_3);
appendString((&T2_), (*field_p1).dbType);
	result = T2_;
	nimln_(48);	{
		NIM_BOOL T5_;
		T5_ = (NIM_BOOL)0;
		T5_ = includePrimaryAndUnique_p2;
		if (!(T5_)) goto LA6_;
		T5_ = (*field_p1).primary;
LA6_: ;
		if (!T5_) goto LA7_;
		nimln_(49);		prepareAdd((&result), 12);
appendString((&result), TM__oxxEQmOSnZEGUk8Yy1EXUw_5);
	}
LA7_: ;
	nimln_(50);	{
		NIM_BOOL T11_;
		T11_ = (NIM_BOOL)0;
		T11_ = includePrimaryAndUnique_p2;
		if (!(T11_)) goto LA12_;
		T11_ = (*field_p1).unique;
LA12_: ;
		if (!T11_) goto LA13_;
		nimln_(51);		prepareAdd((&result), 7);
appendString((&result), TM__oxxEQmOSnZEGUk8Yy1EXUw_7);
	}
LA13_: ;
	nimln_(52);	{
		NIM_BOOL T17_;
		NimStringV2 colontmpD__2;
		NimStringV2 colontmpD__3;
		NimStringV2 T21_;
		NI* T22_;
		T17_ = (NIM_BOOL)0;
		T17_ = isSome__pureZtimes_u4162((*field_p1).maxLength);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T17_)) goto LA18_;
		T17_ = eqStrings((*field_p1).dbType, TM__oxxEQmOSnZEGUk8Yy1EXUw_9);
LA18_: ;
		if (!T17_) goto LA19_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimln_(53);		T21_.len = 0; T21_.p = NIM_NIL;
		T22_ = (NI*)0;
		T22_ = get__pureZtimes_u4246((&(*field_p1).maxLength));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		colontmpD__2 = dollar___systemZdollars_u14((*T22_));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T21_ = rawNewString(colName_1.len + colontmpD__2.len + 21);
appendString((&T21_), TM__oxxEQmOSnZEGUk8Yy1EXUw_11);
appendString((&T21_), colName_1);
appendString((&T21_), TM__oxxEQmOSnZEGUk8Yy1EXUw_13);
appendString((&T21_), colontmpD__2);
appendString((&T21_), TM__oxxEQmOSnZEGUk8Yy1EXUw_17);
		colontmpD__3 = T21_;
		prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
LA19_: ;
	nimlf_(54, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	colontmpD_ = renderDefaultClause__OOZsrcZnimtraZschema_u23(field_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (colName_1.p && !(colName_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colName_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u81)(tyObject_SQLiteDialectcolonObjectType___z2feGCQpY9cMEjqVwJlskEw* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2) {
	NimStringV2 result;
	NimStringV2 colName_1;
	NimStringV2 dbType_1;
	NimStringV2 colontmpD_;
	NimStringV2 T17_;
NIM_BOOL* nimErr_;
	nimfr_("columnDefinitionSqlImpl", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colName_1.len = 0; colName_1.p = NIM_NIL;
	dbType_1.len = 0; dbType_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(57, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	colName_1 = quoteIdent__OOZsrcZnimtraZdialects_u88(&dialect_p0->Sup, (*field_p1).name);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(58);	dbType_1 = (*field_p1).dbType;
	nimln_(59);	{
		if (!eqStrings(dbType_1, TM__oxxEQmOSnZEGUk8Yy1EXUw_43)) goto LA4_;
		nimln_(60);		dbType_1 = TM__oxxEQmOSnZEGUk8Yy1EXUw_44;
	}
LA4_: ;
	nimln_(62);	{
		NIM_BOOL T8_;
		NIM_BOOL T9_;
		NIM_BOOL T10_;
		NimStringV2 T16_;
		T8_ = (NIM_BOOL)0;
		T9_ = (NIM_BOOL)0;
		T10_ = (NIM_BOOL)0;
		T10_ = includePrimaryAndUnique_p2;
		if (!(T10_)) goto LA11_;
		T10_ = (*field_p1).primary;
LA11_: ;
		T9_ = T10_;
		if (!(T9_)) goto LA12_;
		T9_ = (*field_p1).autoincrement;
LA12_: ;
		T8_ = T9_;
		if (!(T8_)) goto LA13_;
		T8_ = eqStrings(dbType_1, TM__oxxEQmOSnZEGUk8Yy1EXUw_46);
LA13_: ;
		if (!T8_) goto LA14_;
		nimln_(63);		nimln_(56);		nimln_(63);		T16_.len = 0; T16_.p = NIM_NIL;
		T16_ = rawNewString(colName_1.len + 34);
appendString((&T16_), colName_1);
appendString((&T16_), TM__oxxEQmOSnZEGUk8Yy1EXUw_48);
		result = T16_;
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (colName_1.p && !(colName_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colName_1.p);
}
		goto BeforeRet_;
	}
LA14_: ;
	nimlf_(64, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	T17_.len = 0; T17_.p = NIM_NIL;
	T17_ = rawNewString(colName_1.len + dbType_1.len + 1);
appendString((&T17_), colName_1);
appendString((&T17_), TM__oxxEQmOSnZEGUk8Yy1EXUw_49);
appendString((&T17_), dbType_1);
	result = T17_;
	nimln_(65);	{
		NIM_BOOL T20_;
		T20_ = (NIM_BOOL)0;
		T20_ = includePrimaryAndUnique_p2;
		if (!(T20_)) goto LA21_;
		T20_ = (*field_p1).primary;
LA21_: ;
		if (!T20_) goto LA22_;
		nimln_(66);		prepareAdd((&result), 12);
appendString((&result), TM__oxxEQmOSnZEGUk8Yy1EXUw_50);
	}
LA22_: ;
	nimln_(67);	{
		NIM_BOOL T26_;
		T26_ = (NIM_BOOL)0;
		T26_ = includePrimaryAndUnique_p2;
		if (!(T26_)) goto LA27_;
		T26_ = (*field_p1).unique;
LA27_: ;
		if (!T26_) goto LA28_;
		nimln_(68);		prepareAdd((&result), 7);
appendString((&result), TM__oxxEQmOSnZEGUk8Yy1EXUw_51);
	}
LA28_: ;
	nimln_(69);	{
		NIM_BOOL T32_;
		NimStringV2 colontmpD__2;
		NimStringV2 colontmpD__3;
		NimStringV2 T36_;
		NI* T37_;
		T32_ = (NIM_BOOL)0;
		T32_ = isSome__pureZtimes_u4162((*field_p1).maxLength);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T32_)) goto LA33_;
		T32_ = eqStrings((*field_p1).dbType, TM__oxxEQmOSnZEGUk8Yy1EXUw_52);
LA33_: ;
		if (!T32_) goto LA34_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimln_(70);		T36_.len = 0; T36_.p = NIM_NIL;
		T37_ = (NI*)0;
		T37_ = get__pureZtimes_u4246((&(*field_p1).maxLength));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		colontmpD__2 = dollar___systemZdollars_u14((*T37_));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T36_ = rawNewString(colName_1.len + colontmpD__2.len + 21);
appendString((&T36_), TM__oxxEQmOSnZEGUk8Yy1EXUw_53);
appendString((&T36_), colName_1);
appendString((&T36_), TM__oxxEQmOSnZEGUk8Yy1EXUw_54);
appendString((&T36_), colontmpD__2);
appendString((&T36_), TM__oxxEQmOSnZEGUk8Yy1EXUw_55);
		colontmpD__3 = T36_;
		prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
LA34_: ;
	nimlf_(71, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	colontmpD_ = renderDefaultClause__OOZsrcZnimtraZschema_u23(field_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (colName_1.p && !(colName_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colName_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u106)(tyObject_PostgresDialectcolonObjectType___nOir5YJqzHpCkOl2gBXFMA* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2) {
	NimStringV2 result;
	NimStringV2 colName_1;
	NimStringV2 dbType_1;
	NimStringV2 colontmpD_;
	NimStringV2 T15_;
NIM_BOOL* nimErr_;
	nimfr_("columnDefinitionSqlImpl", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colName_1.len = 0; colName_1.p = NIM_NIL;
	dbType_1.len = 0; dbType_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(74, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	colName_1 = quoteIdent__OOZsrcZnimtraZdialects_u88(&dialect_p0->Sup, (*field_p1).name);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(75);	dbType_1 = (*field_p1).dbType;
	nimln_(76);	{
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		NIM_BOOL T6_;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T6_ = (NIM_BOOL)0;
		T6_ = includePrimaryAndUnique_p2;
		if (!(T6_)) goto LA7_;
		T6_ = (*field_p1).primary;
LA7_: ;
		T5_ = T6_;
		if (!(T5_)) goto LA8_;
		T5_ = (*field_p1).autoincrement;
LA8_: ;
		T4_ = T5_;
		if (!(T4_)) goto LA9_;
		T4_ = eqStrings(dbType_1, TM__oxxEQmOSnZEGUk8Yy1EXUw_56);
LA9_: ;
		if (!T4_) goto LA10_;
		nimln_(77);		dbType_1 = TM__oxxEQmOSnZEGUk8Yy1EXUw_58;
	}
	goto LA2_;
LA10_: ;
	{
		nimln_(78);		if (!eqStrings(dbType_1, TM__oxxEQmOSnZEGUk8Yy1EXUw_60)) goto LA13_;
		nimln_(79);		dbType_1 = TM__oxxEQmOSnZEGUk8Yy1EXUw_62;
	}
	goto LA2_;
LA13_: ;
LA2_: ;
	nimln_(81);	T15_.len = 0; T15_.p = NIM_NIL;
	T15_ = rawNewString(colName_1.len + dbType_1.len + 1);
appendString((&T15_), colName_1);
appendString((&T15_), TM__oxxEQmOSnZEGUk8Yy1EXUw_63);
appendString((&T15_), dbType_1);
	result = T15_;
	nimln_(82);	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = includePrimaryAndUnique_p2;
		if (!(T18_)) goto LA19_;
		T18_ = (*field_p1).primary;
LA19_: ;
		if (!T18_) goto LA20_;
		nimln_(83);		prepareAdd((&result), 12);
appendString((&result), TM__oxxEQmOSnZEGUk8Yy1EXUw_64);
	}
LA20_: ;
	nimln_(84);	{
		NIM_BOOL T24_;
		T24_ = (NIM_BOOL)0;
		T24_ = includePrimaryAndUnique_p2;
		if (!(T24_)) goto LA25_;
		T24_ = (*field_p1).unique;
LA25_: ;
		if (!T24_) goto LA26_;
		nimln_(85);		prepareAdd((&result), 7);
appendString((&result), TM__oxxEQmOSnZEGUk8Yy1EXUw_65);
	}
LA26_: ;
	nimln_(86);	{
		NIM_BOOL T30_;
		NimStringV2 colontmpD__2;
		NimStringV2 colontmpD__3;
		NimStringV2 T34_;
		NI* T35_;
		T30_ = (NIM_BOOL)0;
		T30_ = isSome__pureZtimes_u4162((*field_p1).maxLength);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T30_)) goto LA31_;
		T30_ = eqStrings((*field_p1).dbType, TM__oxxEQmOSnZEGUk8Yy1EXUw_66);
LA31_: ;
		if (!T30_) goto LA32_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimln_(87);		T34_.len = 0; T34_.p = NIM_NIL;
		T35_ = (NI*)0;
		T35_ = get__pureZtimes_u4246((&(*field_p1).maxLength));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		colontmpD__2 = dollar___systemZdollars_u14((*T35_));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T34_ = rawNewString(colName_1.len + colontmpD__2.len + 21);
appendString((&T34_), TM__oxxEQmOSnZEGUk8Yy1EXUw_67);
appendString((&T34_), colName_1);
appendString((&T34_), TM__oxxEQmOSnZEGUk8Yy1EXUw_68);
appendString((&T34_), colontmpD__2);
appendString((&T34_), TM__oxxEQmOSnZEGUk8Yy1EXUw_69);
		colontmpD__3 = T34_;
		prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
LA32_: ;
	nimlf_(88, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	colontmpD_ = renderDefaultClause__OOZsrcZnimtraZschema_u23(field_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (colName_1.p && !(colName_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colName_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, columnDefinitionSqlImpl__OOZsrcZnimtraZschema_u131)(tyObject_MySQLDialectcolonObjectType___xvaBYabnNV11MO77xZ63xQ* dialect_p0, tyObject_FieldMeta__i1BUMqKsm1K6MAYBgwN3Dw* field_p1, NIM_BOOL includePrimaryAndUnique_p2) {
	NimStringV2 result;
	NimStringV2 colName_1;
	NimStringV2 dbType_1;
	NimStringV2 colontmpD_;
	NimStringV2 T15_;
NIM_BOOL* nimErr_;
	nimfr_("columnDefinitionSqlImpl", "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colName_1.len = 0; colName_1.p = NIM_NIL;
	dbType_1.len = 0; dbType_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(91, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	colName_1 = quoteIdent__OOZsrcZnimtraZdialects_u88(&dialect_p0->Sup, (*field_p1).name);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(92);	dbType_1 = (*field_p1).dbType;
	nimln_(93);	{
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		NIM_BOOL T6_;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T6_ = (NIM_BOOL)0;
		T6_ = includePrimaryAndUnique_p2;
		if (!(T6_)) goto LA7_;
		T6_ = (*field_p1).primary;
LA7_: ;
		T5_ = T6_;
		if (!(T5_)) goto LA8_;
		T5_ = (*field_p1).autoincrement;
LA8_: ;
		T4_ = T5_;
		if (!(T4_)) goto LA9_;
		T4_ = eqStrings(dbType_1, TM__oxxEQmOSnZEGUk8Yy1EXUw_70);
LA9_: ;
		if (!T4_) goto LA10_;
		nimln_(94);		dbType_1 = TM__oxxEQmOSnZEGUk8Yy1EXUw_72;
	}
	goto LA2_;
LA10_: ;
	{
		nimln_(95);		if (!eqStrings(dbType_1, TM__oxxEQmOSnZEGUk8Yy1EXUw_73)) goto LA13_;
		nimln_(96);		dbType_1 = TM__oxxEQmOSnZEGUk8Yy1EXUw_75;
	}
	goto LA2_;
LA13_: ;
LA2_: ;
	nimln_(98);	T15_.len = 0; T15_.p = NIM_NIL;
	T15_ = rawNewString(colName_1.len + dbType_1.len + 1);
appendString((&T15_), colName_1);
appendString((&T15_), TM__oxxEQmOSnZEGUk8Yy1EXUw_76);
appendString((&T15_), dbType_1);
	result = T15_;
	nimln_(99);	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = includePrimaryAndUnique_p2;
		if (!(T18_)) goto LA19_;
		T18_ = (*field_p1).primary;
LA19_: ;
		if (!T18_) goto LA20_;
		nimln_(100);		prepareAdd((&result), 12);
appendString((&result), TM__oxxEQmOSnZEGUk8Yy1EXUw_77);
	}
LA20_: ;
	nimln_(101);	{
		NIM_BOOL T24_;
		T24_ = (NIM_BOOL)0;
		T24_ = includePrimaryAndUnique_p2;
		if (!(T24_)) goto LA25_;
		T24_ = (*field_p1).unique;
LA25_: ;
		if (!T24_) goto LA26_;
		nimln_(102);		prepareAdd((&result), 7);
appendString((&result), TM__oxxEQmOSnZEGUk8Yy1EXUw_78);
	}
LA26_: ;
	nimln_(103);	{
		NIM_BOOL T30_;
		NimStringV2 colontmpD__2;
		NimStringV2 colontmpD__3;
		NimStringV2 T34_;
		NI* T35_;
		T30_ = (NIM_BOOL)0;
		T30_ = isSome__pureZtimes_u4162((*field_p1).maxLength);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T30_)) goto LA31_;
		T30_ = eqStrings((*field_p1).dbType, TM__oxxEQmOSnZEGUk8Yy1EXUw_79);
LA31_: ;
		if (!T30_) goto LA32_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimln_(104);		T34_.len = 0; T34_.p = NIM_NIL;
		T35_ = (NI*)0;
		T35_ = get__pureZtimes_u4246((&(*field_p1).maxLength));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		colontmpD__2 = dollar___systemZdollars_u14((*T35_));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T34_ = rawNewString(colontmpD__2.len + 10);
appendString((&T34_), TM__oxxEQmOSnZEGUk8Yy1EXUw_81);
appendString((&T34_), colontmpD__2);
appendString((&T34_), TM__oxxEQmOSnZEGUk8Yy1EXUw_82);
		colontmpD__3 = T34_;
		prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
LA32_: ;
	nimlf_(105, "/Users/nakagawa_shota/repo/valit/nimtra/src/nimtra/schema.nim");	colontmpD_ = renderDefaultClause__OOZsrcZnimtraZschema_u23(field_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (colName_1.p && !(colName_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colName_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
