/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw;
typedef struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ;
typedef struct tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg;
typedef struct tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA;
typedef struct tyTuple__TGoPjOunaLBwuXSEEclIhw tyTuple__TGoPjOunaLBwuXSEEclIhw;
typedef struct tyObject_Option__QhbJYQKmqNm9ar6sU4SVFfQ tyObject_Option__QhbJYQKmqNm9ar6sU4SVFfQ;
typedef struct tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw;
typedef struct tyObject_TableSnapshot__baF3vyipl6sHCBe0ssDF4w tyObject_TableSnapshot__baF3vyipl6sHCBe0ssDF4w;
typedef struct tySequence__ldrtOldcIK4ucnaUwHkEDw tySequence__ldrtOldcIK4ucnaUwHkEDw;
typedef struct tySequence__ldrtOldcIK4ucnaUwHkEDw_Content tySequence__ldrtOldcIK4ucnaUwHkEDw_Content;
typedef struct tySequence__EcJqHR4nqQX9cAU1lo2nygg tySequence__EcJqHR4nqQX9cAU1lo2nygg;
typedef struct tySequence__EcJqHR4nqQX9cAU1lo2nygg_Content tySequence__EcJqHR4nqQX9cAU1lo2nygg_Content;
typedef struct tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
typedef struct tyObject_ExistingColumn__9cXXLEYHRHskEuaM5izPvdA tyObject_ExistingColumn__9cXXLEYHRHskEuaM5izPvdA;
typedef struct tyObject_ExistingIndex__MvBnA2LALnDrcieE9bt5uLQ tyObject_ExistingIndex__MvBnA2LALnDrcieE9bt5uLQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag {
	Exception Sup;
};
struct tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw {
	tyObject_Defect__g3ALvNr79ahA3rxoG9alxn9ag Sup;
};
struct tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA {
	NI len;
	NI cap;
	tyTuple__TGoPjOunaLBwuXSEEclIhw* d;
};
struct tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg {
	tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw traceStack;
	tyObject_CellSeq__sCES9ctKVcFXlX4RRZb9bsiA toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
typedef NU8 tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw {
	tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw kind;
union{
	struct {
	NI64 intValue;
} _kind_2;
	struct {
	NF floatValue;
} _kind_3;
	struct {
	NimStringV2 textValue;
} _kind_4;
	struct {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blobValue;
} _kind_5;
};
};
struct tyObject_Option__QhbJYQKmqNm9ar6sU4SVFfQ {
	tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw val;
	NIM_BOOL has;
};
struct tySequence__ldrtOldcIK4ucnaUwHkEDw {
  NI len; tySequence__ldrtOldcIK4ucnaUwHkEDw_Content* p;
};
struct tySequence__EcJqHR4nqQX9cAU1lo2nygg {
  NI len; tySequence__EcJqHR4nqQX9cAU1lo2nygg_Content* p;
};
struct tyObject_TableSnapshot__baF3vyipl6sHCBe0ssDF4w {
	NimStringV2 table;
	tySequence__ldrtOldcIK4ucnaUwHkEDw columns;
	tySequence__EcJqHR4nqQX9cAU1lo2nygg indexes;
};
struct tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw {
	tyObject_TableSnapshot__baF3vyipl6sHCBe0ssDF4w val;
	NIM_BOOL has;
};
struct tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw {
	NimStringV2 val;
	NIM_BOOL has;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tyObject_ExistingColumn__9cXXLEYHRHskEuaM5izPvdA {
	NimStringV2 name;
	NimStringV2 dbType;
	NIM_BOOL notNull;
	tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw defaultValue;
	NIM_BOOL primaryKey;
};
struct tySequence__ldrtOldcIK4ucnaUwHkEDw_Content { NI cap; tyObject_ExistingColumn__9cXXLEYHRHskEuaM5izPvdA data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_ExistingIndex__MvBnA2LALnDrcieE9bt5uLQ {
	NimStringV2 name;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ columns;
	NIM_BOOL unique;
};
struct tySequence__EcJqHR4nqQX9cAU1lo2nygg_Content { NI cap; tyObject_ExistingIndex__MvBnA2LALnDrcieE9bt5uLQ data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZoptions_u97)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u4260)(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3520)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3722)(tySequence__qs2FgbZ9c9aoxerHPHQd5foQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZtimes_u4272)(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3041)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3049)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2639)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u5494)(tySequence__ldrtOldcIK4ucnaUwHkEDw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u5649)(tySequence__EcJqHR4nqQX9cAU1lo2nygg dest_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__ldrtOldcIK4ucnaUwHkEDw, eqdup___OOZsrcZnimtraZmigrations_u5500)(tySequence__ldrtOldcIK4ucnaUwHkEDw src_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__EcJqHR4nqQX9cAU1lo2nygg, eqdup___OOZsrcZnimtraZmigrations_u5655)(tySequence__EcJqHR4nqQX9cAU1lo2nygg src_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__VdQkhRirfRSoOEZYCYVm9cw_;
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static NIM_CONST NU32 TM__4DNs4bMUkswhWc4o4dM9bbg_2[4] = {3701606400, 1285336064, 1879817216, 3559163136};
N_LIB_PRIVATE TNimTypeV2 NTIv2__VdQkhRirfRSoOEZYCYVm9cw_ = {.destructor = (void*)rttiDestroy__pureZoptions_u97, .size = sizeof(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw), .align = (NI16) NIM_ALIGNOF(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw), .depth = 3, .display = TM__4DNs4bMUkswhWc4o4dM9bbg_2, .traceImpl = (void*)eqtrace___pureZtimes_u4272, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(375);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(518, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__0GUoEx9abGX8FYLxK5mK3fQ*) (T5_));
		nimlf_(521, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3520(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u4260)(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3722((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZoptions_u97)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZtimes_u4260(((tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");
	nimlf_(360, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/arithmetics.nim");	nimln_(364);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3041)(tyObject_CellSeq__NPL3iGoASB5Gaav9aE9bPGdw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3049(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");
	nimlf_(138, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__JiHTwqSRBBfM6Jn9atZUALg*) (env_p1));
		nimln_(141);		add__system_u3041((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZtimes_u4272)(tyObject_UnpackDefect__VdQkhRirfRSoOEZYCYVm9cw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u2973)(tyObject_Option__QhbJYQKmqNm9ar6sU4SVFfQ* dest_p0) {
	switch ((*dest_p0).val.kind) {
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
	{
		if ((*dest_p0).val._kind_4.textValue.p && !((*dest_p0).val._kind_4.textValue.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).val._kind_4.textValue.p);
}
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
	{
		eqdestroy___pureZtimes_u2639((*dest_p0).val._kind_5.blobValue);
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZnimtraZmigrations_u5862)(tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw* dest_p0, tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw* src_p1) {
	if ((*dest_p0).val.table.p != (*src_p1).val.table.p) {	if ((*dest_p0).val.table.p && !((*dest_p0).val.table.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).val.table.p);
}
	}
(*dest_p0).val.table.len = (*src_p1).val.table.len; (*dest_p0).val.table.p = (*src_p1).val.table.p;
	if ((*dest_p0).val.columns.p != (*src_p1).val.columns.p) {	eqdestroy___OOZsrcZnimtraZmigrations_u5494((*dest_p0).val.columns);
	}
(*dest_p0).val.columns.len = (*src_p1).val.columns.len; (*dest_p0).val.columns.p = (*src_p1).val.columns.p;
	if ((*dest_p0).val.indexes.p != (*src_p1).val.indexes.p) {	eqdestroy___OOZsrcZnimtraZmigrations_u5649((*dest_p0).val.indexes);
	}
(*dest_p0).val.indexes.len = (*src_p1).val.indexes.len; (*dest_p0).val.indexes.p = (*src_p1).val.indexes.p;
	(*dest_p0).has = (*src_p1).has;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZmigrations_u5850)(tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw* dest_p0) {
	(*dest_p0).val.table.len = 0; (*dest_p0).val.table.p = NIM_NIL;
	(*dest_p0).val.columns.len = 0; (*dest_p0).val.columns.p = NIM_NIL;
	(*dest_p0).val.indexes.len = 0; (*dest_p0).val.indexes.p = NIM_NIL;
	(*dest_p0).has = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u5853)(tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw* dest_p0) {
	eqdestroy___OOZsrcZnimtraZmigrations_u5649((*dest_p0).val.indexes);
	eqdestroy___OOZsrcZnimtraZmigrations_u5494((*dest_p0).val.columns);
	if ((*dest_p0).val.table.p && !((*dest_p0).val.table.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).val.table.p);
}
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdup___OOZsrcZnimtraZmigrations_u5859)(tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw* src_p0, tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw* Result) {
	nimZeroMem((void*)Result, sizeof(tyObject_Option__r9b9avK9adfRx79b9blLYwymEyw));
	(*Result).val.table = eqdup___system_u2728((*src_p0).val.table);
	(*Result).val.columns = eqdup___OOZsrcZnimtraZmigrations_u5500((*src_p0).val.columns);
	(*Result).val.indexes = eqdup___OOZsrcZnimtraZmigrations_u5655((*src_p0).val.indexes);
	(*Result).has = (*src_p0).has;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZnimtraZmapper_u326)(tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw* dest_p0, tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw src_p1) {
	if ((*dest_p0).val.p != src_p1.val.p) {	if ((*dest_p0).val.p && !((*dest_p0).val.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).val.p);
}
	}
(*dest_p0).val.len = src_p1.val.len; (*dest_p0).val.p = src_p1.val.p;
	(*dest_p0).has = src_p1.has;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmapper_u317)(tyObject_Option__I8tyuSE9cU6SVI561i8Cz9aw* dest_p0) {
	if ((*dest_p0).val.p && !((*dest_p0).val.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).val.p);
}
}
