/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI* number_p1);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* number_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__pureZparseutils_u388)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* b_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2);
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2);
static N_INLINE(NF, toBiggestFloat__system_u1708)(NI64 i_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, abs__system_u5241)(NF x_p0);
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__pureZparseutils_u325)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
extern TNimTypeV2 NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_;
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__vI9aZNKIcImom6dDyKXW1ZA_8 = { 37 | NIM_STRLIT_FLAG, "Parsed integer outside of valid range" };
static const NimStringV2 TM__vI9aZNKIcImom6dDyKXW1ZA_9 = {37, (NimStrPayload*)&TM__vI9aZNKIcImom6dDyKXW1ZA_8};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2) {
	NIM_BOOL result;
	NI64 r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI64) ((NU64)((NU64)(((NU64) (a_p0))) + (NU64)(((NU64) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NF, toBiggestFloat__system_u1708)(NI64 i_p0) {
	NF result;
	nimfr_("toBiggestFloat", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	nimlf_(1317, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__system_u5241)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2) {
	NIM_BOOL result;
	NI64 r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI64) ((NU64)((NU64)(((NU64) (a_p0))) * (NU64)(((NU64) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toBiggestFloat__system_u1708(a_p0);
	T2_ = (NF)0;
	T2_ = toBiggestFloat__system_u1708(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toBiggestFloat__system_u1708(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__system_u5241(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__system_u5241(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2) {
	NIM_BOOL result;
	NI64 r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI64) ((NU64)((NU64)(((NU64) (a_p0))) - (NU64)(((NU64) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(r_1 ^ (NI64)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__pureZparseutils_u325)(void) {
	tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ* T1_;
	nimfr_("integerOutOfRangeError", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parseutils.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ*) nimNewObj(sizeof(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ), NIM_ALIGNOF(tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__UidSGpWxuIC9bT6QHI0X19aQ_);
	(*T1_).Sup.Sup.name = "ValueError";
	(*T1_).Sup.Sup.message = TM__vI9aZNKIcImom6dDyKXW1ZA_9;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	nimlf_(429, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parseutils.nim");	raiseExceptionEx((Exception*)T1_, "ValueError", "integerOutOfRangeError", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parseutils.nim", 429);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__pureZparseutils_u388)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* b_p1) {
	NI result;
	NI64 sign_1;
	NI i_1;
NIM_BOOL* nimErr_;
	nimfr_("rawParseInt", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parseutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(437);	sign_1 = IL64(-1);
	nimln_(438);	i_1 = ((NI)0);
	nimln_(439);	{
		if (!(i_1 < s_p0Len_0)) goto LA3_;
		nimln_(440);		{
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_2;
			if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
			}
			if (!((NU8)(s_p0[i_1]) == (NU8)(43))) goto LA7_;
			if (nimAddInt(i_1, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_2)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_2);
		}
		goto LA5_;
LA7_: ;
		{
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_3;
			nimln_(441);			if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
			}
			if (!((NU8)(s_p0[i_1]) == (NU8)(45))) goto LA10_;
			nimln_(442);			if (nimAddInt(i_1, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_3)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_3);
			nimln_(443);			sign_1 = IL64(1);
		}
		goto LA5_;
LA10_: ;
LA5_: ;
	}
LA3_: ;
	nimln_(444);	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = (i_1 < s_p0Len_0);
		if (!(T14_)) goto LA15_;
		if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
		}
		T14_ = (((NU8)(s_p0[i_1])) >= ((NU8)(48)) && ((NU8)(s_p0[i_1])) <= ((NU8)(57)));
LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(445);		(*b_p1) = IL64(0);
		{
			nimln_(446);			while (1) {
				NIM_BOOL T20_;
				NI c_1;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_4;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_10;
				T20_ = (NIM_BOOL)0;
				T20_ = (i_1 < s_p0Len_0);
				if (!(T20_)) goto LA21_;
				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				T20_ = (((NU8)(s_p0[i_1])) >= ((NU8)(48)) && ((NU8)(s_p0[i_1])) <= ((NU8)(57)));
LA21_: ;
				if (!T20_) goto LA19;
				nimln_(447);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (nimSubInt(((NU8)(s_p0[i_1])), ((NI)48), &TM__vI9aZNKIcImom6dDyKXW1ZA_4)) { raiseOverflow(); goto BeforeRet_;
				};
				c_1 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4);
				nimln_(448);				{
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_5;
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_6;
					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_7;
					if (nimAddInt64((IL64(-9223372036854775807) - IL64(1)), ((NI64) (c_1)), &TM__vI9aZNKIcImom6dDyKXW1ZA_5)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!((NI64)(((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_5)) / (IL64(10))) <= (*b_p1))) goto LA24_;
					nimln_(449);					if (nimMulInt64((*b_p1), IL64(10), &TM__vI9aZNKIcImom6dDyKXW1ZA_6)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt64((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_6), ((NI64) (c_1)), &TM__vI9aZNKIcImom6dDyKXW1ZA_7)) { raiseOverflow(); goto BeforeRet_;
					};
					(*b_p1) = (NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_7);
				}
				goto LA22_;
LA24_: ;
				{
					nimln_(451);					integerOutOfRangeError__pureZparseutils_u325();
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA22_: ;
				nimln_(452);				if (nimAddInt(i_1, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_10)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_10);
				{
					nimln_(453);					while (1) {
						NIM_BOOL T29_;
						NI TM__vI9aZNKIcImom6dDyKXW1ZA_11;
						T29_ = (NIM_BOOL)0;
						T29_ = (i_1 < s_p0Len_0);
						if (!(T29_)) goto LA30_;
						if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
						}
						T29_ = ((NU8)(s_p0[i_1]) == (NU8)(95));
LA30_: ;
						if (!T29_) goto LA28;
						if (nimAddInt(i_1, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_11)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_11);
					} LA28: ;
				}
			} LA19: ;
		}
		nimln_(454);		{
			NIM_BOOL T33_;
			T33_ = (NIM_BOOL)0;
			T33_ = (sign_1 == IL64(-1));
			if (!(T33_)) goto LA34_;
			T33_ = ((*b_p1) == (IL64(-9223372036854775807) - IL64(1)));
LA34_: ;
			if (!T33_) goto LA35_;
			nimln_(455);			integerOutOfRangeError__pureZparseutils_u325();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA31_;
LA35_: ;
		{
			NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_12;
			nimln_(457);			if (nimMulInt64((*b_p1), sign_1, &TM__vI9aZNKIcImom6dDyKXW1ZA_12)) { raiseOverflow(); goto BeforeRet_;
			};
			(*b_p1) = (NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_12);
			nimln_(458);			result = i_1;
		}
LA31_: ;
	}
	goto LA12_;
LA16_: ;
	{
		nimln_(460);		result = ((NI)0);
	}
LA12_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI64* number_p1) {
	NI result;
	NI64 res_1;
NIM_BOOL* nimErr_;
	nimfr_("parseBiggestInt", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parseutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(476);	res_1 = IL64(0);
	nimln_(479);	result = rawParseInt__pureZparseutils_u388(s_p0, s_p0Len_0, (&res_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(480);	{
		if (!!((result == ((NI)0)))) goto LA3_;
		nimln_(481);		(*number_p1) = res_1;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NIM_CHAR* s_p0, NI s_p0Len_0, NI* number_p1) {
	NI result;
	NI64 res_1;
NIM_BOOL* nimErr_;
	nimfr_("parseInt", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parseutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(492);	res_1 = IL64(0);
	nimln_(493);	result = npuParseBiggestInt(s_p0, s_p0Len_0, (&res_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(497);	{
		if (!!((result == ((NI)0)))) goto LA3_;
		nimln_(498);		(*number_p1) = ((NI) (res_1));
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseInt__pureZparseutils_u981)(NimStringV2 s_p0, NI* number_p1, NI start_p2) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("parseInt", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/parseutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(1019);	nimln_(1028);	if ((s_p0.len-1)-start_p2 != -1 && (start_p2 < 0 || start_p2 >= s_p0.len || (s_p0.len-1) < 0 || (s_p0.len-1) >= s_p0.len)){ raiseIndexError4(start_p2, (s_p0.len-1), s_p0.len); goto BeforeRet_;
	}
	result = npuParseInt((((s_p0).p) ? ((NIM_CHAR*)s_p0.p->data+(start_p2)) : NIM_NIL), ((s_p0.len-1))-(start_p2)+1, number_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
