/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u187)(NimStringV2* result_p0, NI64 x_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__pureZasyncfutures_u275)(tySequence__qs2FgbZ9c9aoxerHPHQd5foQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__pureZasyncfutures_u308)(NimStringV2* s_p0, tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ x_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, addFloat__system_u4837)(NimStringV2* result_p0, NF x_p1);
N_LIB_PRIVATE N_NIMCALL(void, addFloatRoundtrip__system_u4842)(NimStringV2* result_p0, NF x_p1);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_3 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const struct {
  NI cap; NIM_CHAR data[155+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = { 155 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_6 = {155, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_5};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_7 = { 2 | NIM_STRLIT_FLAG, "@[" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_8 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_9 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_10 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_9};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_11 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_12 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_11};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_13 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u34)(NI64 xX60gensym4__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");
	nimlf_(20, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u187((&result), xX60gensym4__p0);
	popFrame();
	return result;
}
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1) {
	addInt__stdZprivateZdigitsutils_u187(result_p0, ((NI64) (x_p1)));
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_4;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), xX60gensym0__p0);
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__pureZasyncfutures_u275)(tySequence__qs2FgbZ9c9aoxerHPHQd5foQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
NIM_BOOL* nimErr_;
	nimfr_("collectionToString", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1715, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	eqcopy___system_u2725((&result), prefix_p1);
	nimlf_(102, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ* value_1;
		NI i_1;
		NI L_1;
		NI T2_;
		value_1 = (tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ*)0;
		nimlf_(249, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = x_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(103, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");				value_1 = (&x_p0.p->data[i_1]);
				nimln_(104);				{
					if (!firstElement_1) goto LA7_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA5_;
LA7_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA5_: ;
				nimln_(116);				addQuoted__pureZasyncfutures_u308((&result), (*value_1));
				nimlf_(13, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T12_;
					T12_ = x_p0.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u95(TM__n49a9aYp5BrbXv9a6OCpJYm0g_6);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			} LA4: ;
		}
	}
	nimlf_(117, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZasyncfutures_u271)(tySequence__qs2FgbZ9c9aoxerHPHQd5foQ x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(133);	result = collectionToString__pureZasyncfutures_u275(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_8, TM__n49a9aYp5BrbXv9a6OCpJYm0g_10, TM__n49a9aYp5BrbXv9a6OCpJYm0g_12);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, addFloat__system_u4837)(NimStringV2* result_p0, NF x_p1) {
NIM_BOOL* nimErr_;
	nimfr_("addFloat", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/formatfloat.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(142, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/std/formatfloat.nim");	addFloatRoundtrip__system_u4842(result_p0, x_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_u4833)(NF x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(14, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_13;
	nimln_(15);	addFloat__system_u4837((&result), x_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
