/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__OaHwijEm2KHEod7LMrnNzA tySequence__OaHwijEm2KHEod7LMrnNzA;
typedef struct tySequence__OaHwijEm2KHEod7LMrnNzA_Content tySequence__OaHwijEm2KHEod7LMrnNzA_Content;
typedef struct tyTuple__732F4NLvyCWp6BvEC0QQAg tyTuple__732F4NLvyCWp6BvEC0QQAg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q;
typedef struct tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw;
typedef struct tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ;
typedef struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ;
typedef struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ tySequence__qs2FgbZ9c9aoxerHPHQd5foQ;
typedef struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content;
typedef struct tySequence__sT17zs9buJfNI7tsy2sxevg tySequence__sT17zs9buJfNI7tsy2sxevg;
typedef struct tySequence__sT17zs9buJfNI7tsy2sxevg_Content tySequence__sT17zs9buJfNI7tsy2sxevg_Content;
typedef struct tyTuple__mjsx0Llj4005VUmJ9boYV6w tyTuple__mjsx0Llj4005VUmJ9boYV6w;
typedef struct tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw;
typedef struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
struct tySequence__OaHwijEm2KHEod7LMrnNzA {
  NI len; tySequence__OaHwijEm2KHEod7LMrnNzA_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw {
	tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw kind;
union{
	struct {
	NI64 intValue;
} _kind_2;
	struct {
	NF floatValue;
} _kind_3;
	struct {
	NimStringV2 textValue;
} _kind_4;
	struct {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blobValue;
} _kind_5;
};
};
struct tyTuple__732F4NLvyCWp6BvEC0QQAg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw Field3;
};
struct tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q {
	tySequence__OaHwijEm2KHEod7LMrnNzA data;
	NI counter;
	NI first;
	NI last;
};
struct tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw {
	NI len;
	void* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ {
  NI len; tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__qs2FgbZ9c9aoxerHPHQd5foQ trace;
	Exception* up;
};
struct tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg {
	Exception Sup;
};
struct tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ {
	tyObject_CatchableError__d1kCVVj9aY0lUORd5Dpjkdg Sup;
};
struct tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ {
	tyObject_ValueError__UidSGpWxuIC9bT6QHI0X19aQ Sup;
};
struct tySequence__sT17zs9buJfNI7tsy2sxevg {
  NI len; tySequence__sT17zs9buJfNI7tsy2sxevg_Content* p;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw {
	NIM_BOOL Field0;
	tySequence__4eRCaZmrYLLw2k30GPTiMw Field1;
};
struct tyTuple__mjsx0Llj4005VUmJ9boYV6w {
	NI Field0;
	NimStringV2 Field1;
	tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw Field2;
};
struct tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw {
	tySequence__sT17zs9buJfNI7tsy2sxevg data;
	NI counter;
};
struct tySequence__OaHwijEm2KHEod7LMrnNzA_Content { NI cap; tyTuple__732F4NLvyCWp6BvEC0QQAg data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__qs2FgbZ9c9aoxerHPHQd5foQ_Content { NI cap; tyObject_StackTraceEntry__JgLJ7b0TzNZvYlrbFKtnZQ data[SEQ_DECL_SIZE]; };
struct tySequence__sT17zs9buJfNI7tsy2sxevg_Content { NI cap; tyTuple__mjsx0Llj4005VUmJ9boYV6w data[SEQ_DECL_SIZE]; };
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2639)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u293)(tySequence__OaHwijEm2KHEod7LMrnNzA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__OOZsrcZnimtraZdriverZbase_u314)(tySequence__OaHwijEm2KHEod7LMrnNzA* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2728)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, eqdup___pureZtimes_u2645)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p0);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2725)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZtimes_u2642)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__OOZsrcZnimtraZmapper_u73)(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q* t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u586)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4460)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NI, rawGet__OOZsrcZnimtraZmigrations_u2670)(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q* t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_u3308)(NimStringV2 key_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u7176)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u7369)(tySequence__sT17zs9buJfNI7tsy2sxevg dest_p0);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u258)(NI x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__OOZsrcZnimtraZmigrations_u7077)(tySequence__sT17zs9buJfNI7tsy2sxevg* s_p0, NI len_p1);
static N_INLINE(NI, rawGet__OOZsrcZnimtraZmigrations_u7536)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZnimtraZmigrations_u8597)(tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw* dest_p0, tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw src_p1);
static N_INLINE(NIM_BOOL, mustRehash__OOZsrcZnimtraZmigrations_u8070)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw t_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZsrcZnimtraZmigrations_u8267)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* t_p0);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0);
static N_INLINE(NF, abs__system_u5241)(NF x_p0);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZsrcZnimtraZmigrations_u8606)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* t_p0, tySequence__sT17zs9buJfNI7tsy2sxevg* data_p1, NimStringV2 key_p2, tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw val_p3, NI hc_p4, NI h_p5);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2722)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZmigrations_u8585)(tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw* dest_p0);
static N_INLINE(NI, rawGetKnownHC__OOZsrcZnimtraZmigrations_u8775)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw t_p0, NimStringV2 key_p1, NI hc_p2);
extern TNimTypeV2 NTIv2__Y3ufay6FmFw9cy5zoiKiFaQ_;
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_5 = { 15 | NIM_STRLIT_FLAG, "key not found: " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_6 = {15, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_5};
static const struct {
  NI cap; NIM_CHAR data[122+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_10 = { 122 | NIM_STRLIT_FLAG, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim(34, 9) `\012t.counter < t.dataLen` " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_11 = {122, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_10};
extern NIM_THREADVAR TFrame* framePtr__system_u2762;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4242;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u293)(tySequence__OaHwijEm2KHEod7LMrnNzA dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field2.p && !(dest_p0.p->data[colontmp_].Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field2.p);
}
			switch (dest_p0.p->data[colontmp_].Field3.kind) {
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
			{
				if (dest_p0.p->data[colontmp_].Field3._kind_4.textValue.p && !(dest_p0.p->data[colontmp_].Field3._kind_4.textValue.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field3._kind_4.textValue.p);
}
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
			{
				eqdestroy___pureZtimes_u2639(dest_p0.p->data[colontmp_].Field3._kind_5.blobValue);
			}
			break;
			default: __builtin_unreachable();
			}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__732F4NLvyCWp6BvEC0QQAg));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u545)(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q* dest_p0) {
	eqdestroy___OOZsrcZnimtraZdriverZbase_u293((*dest_p0).data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZdriverZbase_u542)(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q* dest_p0) {
	(*dest_p0).data.len = 0; (*dest_p0).data.p = NIM_NIL;
	(*dest_p0).counter = 0;
	(*dest_p0).first = 0;
	(*dest_p0).last = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZdriverZbase_u377)(tyTuple__732F4NLvyCWp6BvEC0QQAg* dest_p0) {
	if ((*dest_p0).Field2.p && !((*dest_p0).Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field2.p);
}
	switch ((*dest_p0).Field3.kind) {
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
	{
		if ((*dest_p0).Field3._kind_4.textValue.p && !((*dest_p0).Field3._kind_4.textValue.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field3._kind_4.textValue.p);
}
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
	{
		eqdestroy___pureZtimes_u2639((*dest_p0).Field3._kind_5.blobValue);
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZdriverZbase_u374)(tyTuple__732F4NLvyCWp6BvEC0QQAg* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1 = 0;
	(*dest_p0).Field2.len = 0; (*dest_p0).Field2.p = NIM_NIL;
	(*dest_p0).Field3.kind = 0;
	switch ((*dest_p0).Field3.kind) {
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
	{
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
	{
		(*dest_p0).Field3._kind_2.intValue = 0;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
	{
		(*dest_p0).Field3._kind_3.floatValue = 0;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
	{
		(*dest_p0).Field3._kind_4.textValue.len = 0; (*dest_p0).Field3._kind_4.textValue.p = NIM_NIL;
	}
	break;
	case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
	{
		(*dest_p0).Field3._kind_5.blobValue.len = 0; (*dest_p0).Field3._kind_5.blobValue.p = NIM_NIL;
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(tySequence__OaHwijEm2KHEod7LMrnNzA, eqdup___OOZsrcZnimtraZdriverZbase_u299)(tySequence__OaHwijEm2KHEod7LMrnNzA src_p0) {
	tySequence__OaHwijEm2KHEod7LMrnNzA result;
	NI T1_;
	NI colontmp_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__OOZsrcZnimtraZdriverZbase_u314((&result), T1_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T4_;
			T4_ = result.len;
			if (!(colontmp_ < T4_)) goto LA3;
			result.p->data[colontmp_].Field0 = src_p0.p->data[colontmp_].Field0;
			result.p->data[colontmp_].Field1 = src_p0.p->data[colontmp_].Field1;
			result.p->data[colontmp_].Field2 = eqdup___system_u2728(src_p0.p->data[colontmp_].Field2);
			result.p->data[colontmp_].Field3.kind = src_p0.p->data[colontmp_].Field3.kind;
			switch (result.p->data[colontmp_].Field3.kind) {
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
			{
				result.p->data[colontmp_].Field3._kind_2.intValue = src_p0.p->data[colontmp_].Field3._kind_2.intValue;
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
			{
				result.p->data[colontmp_].Field3._kind_3.floatValue = src_p0.p->data[colontmp_].Field3._kind_3.floatValue;
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
			{
				result.p->data[colontmp_].Field3._kind_4.textValue = eqdup___system_u2728(src_p0.p->data[colontmp_].Field3._kind_4.textValue);
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
			{
				result.p->data[colontmp_].Field3._kind_5.blobValue = eqdup___pureZtimes_u2645(src_p0.p->data[colontmp_].Field3._kind_5.blobValue);
			}
			break;
			default: __builtin_unreachable();
			}
			colontmp_ += ((NI)1);
		} LA3: ;
	}
	return result;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw*) (x_p0))).p == (*((tyObject_NimRawSeq__oLGRfERDypJWk9crPbd8kdw*) (y_p1))).p);
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZnimtraZdriverZbase_u296)(tySequence__OaHwijEm2KHEod7LMrnNzA* dest_p0, tySequence__OaHwijEm2KHEod7LMrnNzA src_p1) {
	NI T6_;
	NI colontmp_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__OOZsrcZnimtraZdriverZbase_u314((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw colontmp__2;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			(*dest_p0).p->data[colontmp_].Field0 = src_p1.p->data[colontmp_].Field0;
			(*dest_p0).p->data[colontmp_].Field1 = src_p1.p->data[colontmp_].Field1;
			eqcopy___system_u2725((&(*dest_p0).p->data[colontmp_].Field2), src_p1.p->data[colontmp_].Field2);
			colontmp__2 = (*dest_p0).p->data[colontmp_].Field3;
			nimZeroMem((void*)(&(*dest_p0).p->data[colontmp_].Field3), sizeof(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw));
			(*dest_p0).p->data[colontmp_].Field3.kind = src_p1.p->data[colontmp_].Field3.kind;
			switch ((*dest_p0).p->data[colontmp_].Field3.kind) {
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
			{
				(*dest_p0).p->data[colontmp_].Field3._kind_2.intValue = 0;
				(*dest_p0).p->data[colontmp_].Field3._kind_2.intValue = src_p1.p->data[colontmp_].Field3._kind_2.intValue;
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
			{
				(*dest_p0).p->data[colontmp_].Field3._kind_3.floatValue = 0;
				(*dest_p0).p->data[colontmp_].Field3._kind_3.floatValue = src_p1.p->data[colontmp_].Field3._kind_3.floatValue;
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
			{
				(*dest_p0).p->data[colontmp_].Field3._kind_4.textValue.len = 0; (*dest_p0).p->data[colontmp_].Field3._kind_4.textValue.p = NIM_NIL;
				eqcopy___system_u2725((&(*dest_p0).p->data[colontmp_].Field3._kind_4.textValue), src_p1.p->data[colontmp_].Field3._kind_4.textValue);
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
			{
				(*dest_p0).p->data[colontmp_].Field3._kind_5.blobValue.len = 0; (*dest_p0).p->data[colontmp_].Field3._kind_5.blobValue.p = NIM_NIL;
				eqcopy___pureZtimes_u2642((&(*dest_p0).p->data[colontmp_].Field3._kind_5.blobValue), src_p1.p->data[colontmp_].Field3._kind_5.blobValue);
			}
			break;
			default: __builtin_unreachable();
			}
			switch (colontmp__2.kind) {
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)0):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)1):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)2):
			{
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)3):
			{
				if (colontmp__2._kind_4.textValue.p && !(colontmp__2._kind_4.textValue.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp__2._kind_4.textValue.p);
}
			}
			break;
			case ((tyEnum_SqlValueKind__CfRC9aHCoZjxc9a0SnYVLKGw)4):
			{
				eqdestroy___pureZtimes_u2639(colontmp__2._kind_5.blobValue);
			}
			break;
			default: __builtin_unreachable();
			}
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2762 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2762).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2762;
	framePtr__system_u2762 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4460();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2762 = (*framePtr__system_u2762).prev;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isFilled", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");
	nimlf_(27, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");	result = !((hcode_p0 == ((NI)0)));
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");
{	nimlf_(33, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_2;
	nimfr_("nextTry", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");
{	result = (NI)0;
	nimlf_(30, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");	if (nimAddInt(h_p0, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_2)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_2) & maxHash_p1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4242);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__OOZsrcZnimtraZmapper_u73)(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q* t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_3;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(72);	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u586(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = (*t_p0).data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimlf_(1357, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");		nimlf_(43, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = ((*t_p0).data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T17_ = ((*t_p0).data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T17_ = eqStrings((*t_p0).data.p->data[h_1].Field2, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimlf_(1357, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");				nimlf_(51, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = ((*t_p0).data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_3)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_3);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__OOZsrcZnimtraZmapper_u54)(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q* t_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("hasKey", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(1503, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");	hc_1 = 0;
	nimln_(1504);	T1_ = (NI)0;
	T1_ = rawGet__OOZsrcZnimtraZmapper_u73(t_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGet__OOZsrcZnimtraZmigrations_u2670)(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q* t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_4;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(72, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u586(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = (*t_p0).data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimln_(75);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = ((*t_p0).data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T17_ = ((*t_p0).data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T17_ = eqStrings((*t_p0).data.p->data[h_1].Field2, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimln_(75);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = ((*t_p0).data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_4)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_4);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_u3308)(NimStringV2 key_p0) {
	tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ* T1_;
	NimStringV2 T2_;
	nimfr_("raiseKeyError", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ*) nimNewObj(sizeof(tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ), NIM_ALIGNOF(tyObject_KeyError__Y3ufay6FmFw9cy5zoiKiFaQ));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__Y3ufay6FmFw9cy5zoiKiFaQ_);
	(*T1_).Sup.Sup.Sup.name = "KeyError";
	nimlf_(232, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(key_p0.len + 15);
appendString((&T2_), TM__4SoG2KRQy3oMm9aUzSLtGrA_6);
appendString((&T2_), key_p0);
	(*T1_).Sup.Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "KeyError", "raiseKeyError", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim", 232);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw*, X5BX5D___OOZsrcZnimtraZmigrations_u2663)(tyObject_OrderedTable__i041CeWus8OBglhRP2U15Q* t_p0, NimStringV2 key_p1) {
	tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw* result;
	NI hcX60gensym95__1;
	NI indexX60gensym95__1;
NIM_BOOL* nimErr_;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_SqlValue__sn2t7k9b5xBT84qX5wDn8nw*)0;
	hcX60gensym95__1 = (NI)0;
	nimln_(241);	indexX60gensym95__1 = rawGet__OOZsrcZnimtraZmigrations_u2670(t_p0, key_p1, (&hcX60gensym95__1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1469);	{
		nimln_(242);		if (!(((NI)0) <= indexX60gensym95__1)) goto LA3_;
		if (indexX60gensym95__1 < 0 || indexX60gensym95__1 >= (*t_p0).data.len){ raiseIndexError2(indexX60gensym95__1,(*t_p0).data.len-1); goto BeforeRet_;
		}
		result = (&(*t_p0).data.p->data[indexX60gensym95__1].Field3);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(244);		raiseKeyError__pureZjson_u3308(key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u7369)(tySequence__sT17zs9buJfNI7tsy2sxevg dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field1.p && !(dest_p0.p->data[colontmp_].Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field1.p);
}
			eqdestroy___OOZsrcZnimtraZmigrations_u7176(dest_p0.p->data[colontmp_].Field2.Field1);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__mjsx0Llj4005VUmJ9boYV6w));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZnimtraZmigrations_u7360)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* dest_p0, tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw src_p1) {
	if ((*dest_p0).data.p != src_p1.data.p) {	eqdestroy___OOZsrcZnimtraZmigrations_u7369((*dest_p0).data);
	}
(*dest_p0).data.len = src_p1.data.len; (*dest_p0).data.p = src_p1.data.p;
	(*dest_p0).counter = src_p1.counter;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_7;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_8;
NIM_BOOL* nimErr_;
	nimfr_("slotsNeeded", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(39, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");	if (nimAddInt((NI)((count_p0) / (((NI)2))), count_p0, &TM__4SoG2KRQy3oMm9aUzSLtGrA_7)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_7), ((NI)4), &TM__4SoG2KRQy3oMm9aUzSLtGrA_8)) { raiseOverflow(); goto BeforeRet_;
	};
	result = nextPowerOfTwo__pureZmath_u258((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_8));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u7155)(tyTuple__mjsx0Llj4005VUmJ9boYV6w* dest_p0) {
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
	eqdestroy___OOZsrcZnimtraZmigrations_u7176((*dest_p0).Field2.Field1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZnimtraZmigrations_u7152)(tyTuple__mjsx0Llj4005VUmJ9boYV6w* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1.len = 0; (*dest_p0).Field1.p = NIM_NIL;
	(*dest_p0).Field2.Field0 = 0;
	(*dest_p0).Field2.Field1.len = 0; (*dest_p0).Field2.Field1.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw, initTable__OOZsrcZnimtraZmigrations_u7063)(NI initialSize_p0) {
	tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw result;
	NI correctSizeX60gensym235__1;
NIM_BOOL* nimErr_;
	nimfr_("initTable", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(281, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw));
	nimlf_(182, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tableimpl.nim");	if ((initialSize_p0) < ((NI)0) || (initialSize_p0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p0, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	correctSizeX60gensym235__1 = slotsNeeded__pureZcollectionsZtables_u42((initialSize_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(186);	result.counter = ((NI)0);
	nimln_(187);	if ((correctSizeX60gensym235__1) < ((NI)0) || (correctSizeX60gensym235__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym235__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__OOZsrcZnimtraZmigrations_u7077((&result.data), (correctSizeX60gensym235__1));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZnimtraZmigrations_u7351)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* dest_p0) {
	eqdestroy___OOZsrcZnimtraZmigrations_u7369((*dest_p0).data);
}
static N_INLINE(NI, rawGet__OOZsrcZnimtraZmigrations_u7536)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_9;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(72, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u586(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = t_p0.data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimln_(75);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = (t_p0.data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZtables_u31(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimln_(75);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_9)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_9);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__OOZsrcZnimtraZmigrations_u7529)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw t_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("hasKey", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc_1 = (NI)0;
	nimlf_(371, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");	T1_ = (NI)0;
	T1_ = rawGet__OOZsrcZnimtraZmigrations_u7536(t_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__OOZsrcZnimtraZmigrations_u8070)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw t_p0) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_12;
	NI T9_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_13;
NIM_BOOL* nimErr_;
	nimfr_("mustRehash", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(34, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!!((t_p0.counter < T3_))) goto LA4_;
		failedAssertImpl__stdZassertions_u95(TM__4SoG2KRQy3oMm9aUzSLtGrA_11);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimln_(35);	T6_ = (NIM_BOOL)0;
	T7_ = t_p0.data.len;
	if (nimAddInt(t_p0.counter, (NI)((t_p0.counter) / (((NI)2))), &TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = (T7_ < (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12));
	if (T6_) goto LA8_;
	T9_ = t_p0.data.len;
	if (nimSubInt(T9_, t_p0.counter, &TM__4SoG2KRQy3oMm9aUzSLtGrA_13)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_13) < ((NI)4));
LA8_: ;
	result = T6_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0) {
	NF result;
	nimfr_("toFloat", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");
	nimlf_(1302, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__system_u5241)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toFloat__system_u1705(a_p0);
	T2_ = (NF)0;
	T2_ = toFloat__system_u1705(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toFloat__system_u1705(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__system_u5241(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__system_u5241(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZsrcZnimtraZmigrations_u8606)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* t_p0, tySequence__sT17zs9buJfNI7tsy2sxevg* data_p1, NimStringV2 key_p2, tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw val_p3, NI hc_p4, NI h_p5) {
	nimfr_("rawInsert", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tableimpl.nim");
{	nimln_(1715);	if (h_p5 < 0 || h_p5 >= (*data_p1).len){ raiseIndexError2(h_p5,(*data_p1).len-1); goto BeforeRet_;
	}
	eqcopy___system_u2725((&(*data_p1).p->data[h_p5].Field1), key_p2);
	nimln_(170);	if (h_p5 < 0 || h_p5 >= (*data_p1).len){ raiseIndexError2(h_p5,(*data_p1).len-1); goto BeforeRet_;
	}
	eqsink___OOZsrcZnimtraZmigrations_u8597((&(*data_p1).p->data[h_p5].Field2), val_p3);
	nimlf_(27, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tableimpl.nim");	if (h_p5 < 0 || h_p5 >= (*data_p1).len){ raiseIndexError2(h_p5,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p5].Field0 = hc_p4;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZsrcZnimtraZmigrations_u8267)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* t_p0) {
	tySequence__sT17zs9buJfNI7tsy2sxevg n_1;
	NI T1_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_14;
	tySequence__sT17zs9buJfNI7tsy2sxevg T2_;
NIM_BOOL* nimErr_;
	nimfr_("enlarge", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	nimlf_(248, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");	T1_ = (*t_p0).data.len;
	if (nimMulInt(T1_, ((NI)2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) < ((NI)0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__OOZsrcZnimtraZmigrations_u7077((&n_1), ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14)));
	nimln_(249);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*t_p0).data;
	(*t_p0).data = n_1;
	n_1 = T2_;
	{
		NI i_1;
		NI colontmp_;
		NI T4_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(46, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		nimlf_(250, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");		T4_ = (n_1.len-1);
		colontmp_ = T4_;
		nimlf_(68, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(69);			while (1) {
				NI eh_1;
				NI TM__4SoG2KRQy3oMm9aUzSLtGrA_15;
				if (!(res_1 <= colontmp_)) goto LA6;
				nimlf_(250, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");				i_1 = ((NI) (res_1));
				nimln_(251);				if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
				}
				eh_1 = n_1.p->data[i_1].Field0;
				nimln_(252);				{
					NIM_BOOL T9_;
					NimStringV2 colontmpD_;
					NI j_1;
					NI T12_;
					tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* T17_;
					tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw T18_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZtables_u31(eh_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					nimln_(253);					T12_ = ((*t_p0).data.len-1);
					j_1 = (NI)(eh_1 & T12_);
					{
						nimln_(254);						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if (j_1 < 0 || j_1 >= (*t_p0).data.len){ raiseIndexError2(j_1,(*t_p0).data.len-1); goto BeforeRet_;
							}
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[j_1].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T15_) goto LA14;
							nimln_(255);							T16_ = ((*t_p0).data.len-1);
							j_1 = nextTry__pureZcollectionsZtables_u34(j_1, T16_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						} LA14: ;
					}
					nimln_(259);					T17_ = (tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw*)0;
					T17_ = t_p0;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					colontmpD_ = n_1.p->data[i_1].Field1;
					eqwasMoved___system_u2722((&n_1.p->data[i_1].Field1));
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T18_ = n_1.p->data[i_1].Field2;
					eqwasMoved___OOZsrcZnimtraZmigrations_u8585((&n_1.p->data[i_1].Field2));
					rawInsert__OOZsrcZnimtraZmigrations_u8606(T17_, (&(*t_p0).data), colontmpD_, T18_, eh_1, j_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimlf_(394, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
LA10_: ;
				nimlf_(74, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_15)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_15);
			} LA6: ;
		}
	}
	nimlf_(281, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");	eqdestroy___OOZsrcZnimtraZmigrations_u7369(n_1);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, rawGetKnownHC__OOZsrcZnimtraZmigrations_u8775)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw t_p0, NimStringV2 key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_16;
NIM_BOOL* nimErr_;
	nimfr_("rawGetKnownHC", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(42, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/hashcommon.nim");	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(43);		nimln_(55);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(44);	T6_ = (t_p0.data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_u31(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			nimln_(50);			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				nimln_(51);				nimln_(55);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			nimln_(52);			T16_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_16)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_16);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZsrcZnimtraZmigrations_u7865)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* t_p0, NimStringV2 key_p1, tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw val_p2) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("[]=", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(58, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tableimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym243__1;
		nimln_(37);		T3_ = (*t_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(182);		correctSizeX60gensym243__1 = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(186);		(*t_p0).counter = ((NI)0);
		nimln_(187);		if ((correctSizeX60gensym243__1) < ((NI)0) || (correctSizeX60gensym243__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym243__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__OOZsrcZnimtraZmigrations_u7077((&(*t_p0).data), (correctSizeX60gensym243__1));
	}
LA4_: ;
	nimln_(59);	hc_1 = 0;
	nimln_(60);	index_1 = rawGet__OOZsrcZnimtraZmigrations_u7536((*t_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(298, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");	{
		nimlf_(61, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tableimpl.nim");		if (!(((NI)0) <= index_1)) goto LA8_;
		nimlf_(170, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/system.nim");		if (index_1 < 0 || index_1 >= (*t_p0).data.len){ raiseIndexError2(index_1,(*t_p0).data.len-1); goto BeforeRet_;
		}
		eqsink___OOZsrcZnimtraZmigrations_u8597((&(*t_p0).data.p->data[index_1].Field2), val_p2);
	}
	goto LA6_;
LA8_: ;
	{
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_17;
		tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* T21_;
		tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw blitTmp_1;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_18;
		nimlf_(49, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tableimpl.nim");		{
			NI T13_;
			NI correctSizeX60gensym246__1;
			nimln_(37);			T13_ = (*t_p0).data.len;
			if (!(T13_ == ((NI)0))) goto LA14_;
			nimln_(182);			correctSizeX60gensym246__1 = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(186);			(*t_p0).counter = ((NI)0);
			nimln_(187);			if ((correctSizeX60gensym246__1) < ((NI)0) || (correctSizeX60gensym246__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym246__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			newSeq__OOZsrcZnimtraZmigrations_u7077((&(*t_p0).data), (correctSizeX60gensym246__1));
		}
LA14_: ;
		nimln_(50);		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__OOZsrcZnimtraZmigrations_u8070((*t_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T18_) goto LA19_;
			nimln_(51);			enlarge__OOZsrcZnimtraZmigrations_u8267(t_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(52);			index_1 = rawGetKnownHC__OOZsrcZnimtraZmigrations_u8775((*t_p0), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA19_: ;
		nimln_(53);		if (nimSubInt(((NI)-1), index_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_17)) { raiseOverflow(); goto BeforeRet_;
		};
		index_1 = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_17);
		nimln_(54);		T21_ = (tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw*)0;
		T21_ = t_p0;
		nimln_(62);		blitTmp_1 = val_p2;
		nimln_(54);		rawInsert__OOZsrcZnimtraZmigrations_u8606(T21_, (&(*t_p0).data), key_p1, blitTmp_1, hc_1, index_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(62);		if (nimAddInt((*t_p0).counter, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_18)) { raiseOverflow(); goto BeforeRet_;
		};
		(*t_p0).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_18);
	}
LA6_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw*, X5BX5D___OOZsrcZnimtraZmigrations_u9080)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw* t_p0, NimStringV2 key_p1) {
	tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw* result;
	NI hcX60gensym22__1;
	NI indexX60gensym22__1;
NIM_BOOL* nimErr_;
	nimfr_("[]", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
{nimErr_ = nimErrorFlag();
	result = (tyTuple__d6s5rZNqB4Ecv0ZXaGy6Hw*)0;
	hcX60gensym22__1 = (NI)0;
	nimlf_(241, "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");	indexX60gensym22__1 = rawGet__OOZsrcZnimtraZmigrations_u7536((*t_p0), key_p1, (&hcX60gensym22__1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(353);	{
		nimln_(242);		if (!(((NI)0) <= indexX60gensym22__1)) goto LA3_;
		if (indexX60gensym22__1 < 0 || indexX60gensym22__1 >= (*t_p0).data.len){ raiseIndexError2(indexX60gensym22__1,(*t_p0).data.len-1); goto BeforeRet_;
		}
		result = (&(*t_p0).data.p->data[indexX60gensym22__1].Field2);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(244);		raiseKeyError__pureZjson_u3308(key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__OOZsrcZnimtraZmigrations_u9251)(tyObject_Table__DTmQlGkwn1CjdvfsLSA6Rw t_p0) {
	NI result;
	nimfr_("len", "/Users/nakagawa_shota/.choosenim/toolchains/nim-2.2.8/lib/pure/collections/tables.nim");
	nimln_(495);	result = t_p0.counter;
	popFrame();
	return result;
}
