/* Generated by Nim Compiler v2.2.8 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType___3Jl03u5E4vlptQdP9b2y9bLg tyObject_TimezonecolonObjectType___3Jl03u5E4vlptQdP9b2y9bLg;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___3Jl03u5E4vlptQdP9b2y9bLg* utcInstance__pureZtimes_u2039;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___3Jl03u5E4vlptQdP9b2y9bLg* localInstance__pureZtimes_u2040;
